[package]
name = "aliveness"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
configparser = { version = "3.0.2", features = ["async-std"] }
dbus = { version = "0.9.7", features = ["futures"] }
dbus-tokio = "0.7.5"
futures-channel = "0.3.25"
futures-util = "0.3.25"
hostname = "0.3.1"
hula-types = { path = "../hula/types/" }
network-interface = "0.1.5"
regex = "1.7.0"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["full"] }
zbus = { version = "3.7.0", features = ["tokio"] }
