[package]
name = "hulk_widgets"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
egui.workspace = true
egui_extras.workspace = true
nucleo-matcher.workspace = true
