# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools/mate/src/mate/ui/views/plot/plot_view.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PlotView(object):
    def setupUi(self, PlotView):
        PlotView.setObjectName("PlotView")
        PlotView.resize(510, 556)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_plot = QtWidgets.QWidget()
        self.tab_plot.setObjectName("tab_plot")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_plot)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.plot_widget = PlotWidget(self.tab_plot)
        self.plot_widget.setObjectName("plot_widget")
        self.verticalLayout_5.addWidget(self.plot_widget)
        self.btnSnap = QtWidgets.QPushButton(self.tab_plot)
        self.btnSnap.setObjectName("btnSnap")
        self.verticalLayout_5.addWidget(self.btnSnap)
        self.tabWidget.addTab(self.tab_plot, "")
        self.tab_config = QtWidgets.QWidget()
        self.tab_config.setObjectName("tab_config")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_config)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_config)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.groupBox.setObjectName("groupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_3.setObjectName("formLayout_3")
        self.fPSLabel = QtWidgets.QLabel(self.groupBox)
        self.fPSLabel.setObjectName("fPSLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fPSLabel)
        self.spin_fps = QtWidgets.QSpinBox(self.groupBox)
        self.spin_fps.setObjectName("spin_fps")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_fps)
        self.bufferLabel = QtWidgets.QLabel(self.groupBox)
        self.bufferLabel.setObjectName("bufferLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.bufferLabel)
        self.spin_buffer = QtWidgets.QSpinBox(self.groupBox)
        self.spin_buffer.setObjectName("spin_buffer")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_buffer)
        self.legendLabel = QtWidgets.QLabel(self.groupBox)
        self.legendLabel.setObjectName("legendLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.legendLabel)
        self.legendCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.legendCheckBox.setObjectName("legendCheckBox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.legendCheckBox)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.splitter = QtWidgets.QSplitter(self.tab_config)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddCurve = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddCurve.sizePolicy().hasHeightForWidth())
        self.btnAddCurve.setSizePolicy(sizePolicy)
        self.btnAddCurve.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btnAddCurve.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.btnAddCurve.setObjectName("btnAddCurve")
        self.horizontalLayout.addWidget(self.btnAddCurve)
        self.btnDeleteCurve = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeleteCurve.sizePolicy().hasHeightForWidth())
        self.btnDeleteCurve.setSizePolicy(sizePolicy)
        self.btnDeleteCurve.setObjectName("btnDeleteCurve")
        self.horizontalLayout.addWidget(self.btnDeleteCurve)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.formWidget = QtWidgets.QWidget(self.splitter)
        self.formWidget.setEnabled(False)
        self.formWidget.setObjectName("formWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.formWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.formWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formWidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.enabledLabel = QtWidgets.QLabel(self.formWidget)
        self.enabledLabel.setObjectName("enabledLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.enabledLabel)
        self.enabledCheckBox = QtWidgets.QCheckBox(self.formWidget)
        self.enabledCheckBox.setObjectName("enabledCheckBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.enabledCheckBox)
        self.keyLabel = QtWidgets.QLabel(self.formWidget)
        self.keyLabel.setObjectName("keyLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.keyLabel)
        self.cbxKey = QtWidgets.QComboBox(self.formWidget)
        self.cbxKey.setEditable(True)
        self.cbxKey.setObjectName("cbxKey")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbxKey)
        self.lambdaWidget = QtWidgets.QWidget(self.formWidget)
        self.lambdaWidget.setObjectName("lambdaWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.lambdaWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.lambdaWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.edit_lambda = QtWidgets.QTextEdit(self.lambdaWidget)
        self.edit_lambda.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_lambda.setObjectName("edit_lambda")
        self.verticalLayout_6.addWidget(self.edit_lambda)
        self.label = QtWidgets.QLabel(self.lambdaWidget)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lambdaWidget)
        self.colorLabel = QtWidgets.QLabel(self.formWidget)
        self.colorLabel.setObjectName("colorLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.colorLabel)
        self.colorWidget = QtWidgets.QWidget(self.formWidget)
        self.colorWidget.setObjectName("colorWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.colorWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.edit_color = QtWidgets.QLineEdit(self.colorWidget)
        self.edit_color.setObjectName("edit_color")
        self.horizontalLayout_3.addWidget(self.edit_color)
        self.btnColor = QtWidgets.QPushButton(self.colorWidget)
        self.btnColor.setFlat(False)
        self.btnColor.setObjectName("btnColor")
        self.horizontalLayout_3.addWidget(self.btnColor)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.colorWidget)
        self.verticalLayout_4.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAccept = QtWidgets.QPushButton(self.formWidget)
        self.btnAccept.setObjectName("btnAccept")
        self.horizontalLayout_2.addWidget(self.btnAccept)
        self.btnDiscard = QtWidgets.QPushButton(self.formWidget)
        self.btnDiscard.setObjectName("btnDiscard")
        self.horizontalLayout_2.addWidget(self.btnDiscard)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.splitter)
        self.tabWidget.addTab(self.tab_config, "")
        self.verticalLayout.addWidget(self.tabWidget)
        PlotView.setWidget(self.dockWidgetContents)

        self.retranslateUi(PlotView)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PlotView)

    def retranslateUi(self, PlotView):
        _translate = QtCore.QCoreApplication.translate
        PlotView.setWindowTitle(_translate("PlotView", "PlotView"))
        self.btnSnap.setText(_translate("PlotView", "Snap"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plot), _translate("PlotView", "Plot"))
        self.groupBox.setTitle(_translate("PlotView", "General"))
        self.fPSLabel.setText(_translate("PlotView", "FPS:"))
        self.bufferLabel.setText(_translate("PlotView", "buffer"))
        self.legendLabel.setText(_translate("PlotView", "Legend"))
        self.btnAddCurve.setText(_translate("PlotView", "Add"))
        self.btnDeleteCurve.setText(_translate("PlotView", "Delete"))
        self.nameLabel.setText(_translate("PlotView", "Name:"))
        self.enabledLabel.setText(_translate("PlotView", "Enabled:"))
        self.keyLabel.setText(_translate("PlotView", "Key:"))
        self.label_2.setText(_translate("PlotView", "def parse(input):"))
        self.label.setText(_translate("PlotView", "return output"))
        self.colorLabel.setText(_translate("PlotView", "Color:"))
        self.btnColor.setText(_translate("PlotView", "Pick"))
        self.btnAccept.setText(_translate("PlotView", "Accept"))
        self.btnDiscard.setText(_translate("PlotView", "Discard"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), _translate("PlotView", "Config"))

from pyqtgraph import PlotWidget
