[package]
name = "whistle_detection"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
color-eyre = { workspace = true }
context_attribute = { workspace = true }
filtering = { workspace = true }
framework = { workspace = true }
hardware = { workspace = true }
ros-z = { workspace = true }
rustfft = { workspace = true }
serde = { workspace = true, features = ["derive"] }
types = { workspace = true }
