#!/usr/bin/env bash

BASEDIR=$(realpath $(dirname $0))

NODE_VERSION="v8.9.1"
NODE_URL="https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.xz"
NODE_TAR=$(basename $NODE_URL)
NODE_TARGET="$BASEDIR/node"
NODE_PATH="$NODE_TARGET/node-$NODE_VERSION-linux-x64/bin"

if [ ! -d $NODE_PATH ]; then
    echo "Downloading node..."
    mkdir -p $NODE_TARGET
    wget -P $NODE_TARGET "$NODE_URL"
    tar -C "$NODE_TARGET" -xf "$BASEDIR/node/$NODE_TAR"
fi

PATH="$NODE_PATH:$PATH"

cd $BASEDIR
npm $*
