#!/usr/bin/env bash

BASEDIR=$(realpath $(dirname $0))

npm="$BASEDIR/npmw"

header() {
    echo "################## $* ##################"
}

copy_by_extension() {
    FROM=$1
    TO=$2
    EXT=$3
    for FILE in $(find "$FROM" -name "*.$EXT"); do
        REL_DIR=$(dirname $(realpath --relative-to "$FROM" "$FILE"))
        mkdir -p "$TO/$REL_DIR"
        cp -v "$FILE" "$TO/$REL_DIR"
    done
}

if [ "$1" == "-b" ]; then
    header "Installing Dependencies"
    $npm install
    header "Running build"
    $npm run build
    header "Copy assets"
    copy_by_extension "$BASEDIR/src/ofa/client" "$BASEDIR/build/ofa/public" "html"
fi

if [ "$1" == "-c" ] || [ "$1" == "--client" ]; then
    header "Watching client source files and starting OFA"
    $npm run serve:client
    exit 0
fi

if [ "$1" == "-s" ] || [ "$1" == "--server" ]; then
    header "Watching server source files and starting OFA"
    $npm run serve:server
    exit 0
fi

if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
    echo "Ofa quickstart script. Usage: ofa [options]"
    echo "Options:"
    echo -e "\t-b\t\tBuild before run."
    echo -e "\t-c,--client\tRun and build client source files everytime something changes."
    echo -e "\t-s,--server\tRun and build server source files everytime something changes."
    echo -e "\t-h,--help\tShow this help message."
    exit 0
fi

if [ ! -f "$BASEDIR/build/ofa/index.js" ]; then
    echo "Ofa was not built yet. Please use '-b' option to build before run."
    exit 1
fi

header "Starting OFA"
$npm run start
