[package]
edition = "2021"
license = "GPL-3.0-only"
name = "structs"
version = "0.1.0"

[dependencies]

[build-dependencies]
anyhow = "1.0.59"
convert_case = "0.5.0"
proc-macro2 = {version = "1.0.39", features = ["span-locations"]}
quote = "1.0.10"
source_analyzer = {path = "../source_analyzer"}
