[package]
edition = "2021"
license = "GPL-3.0-only"
name = "structs"
version = "0.1.0"

[dependencies]
color-eyre = { workspace = true }
filtering = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serialize_hierarchy = { workspace = true }
spl_network_messages = { workspace = true }
types = { workspace = true }

[build-dependencies]
build_script_helpers = { workspace = true }
color-eyre = { workspace = true }
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
source_analyzer = { workspace = true }
