opponent = "R-ZWEI_KICKERS"
phase = "second-half"
location = "go25"
wifi = "SPL_A"
base = "hulk/main"
branches = [
  "schmidma/referee-silence-interval",
  "schmidma/no-lines-during-standup",
  "schluis/inside-turn-kicks",
  "Franziska-Sophie/field-color-detection",
  "paudar/defender-searcher-delay",
  "schluis/anti-x-legs",
]
assignments = [
  "37:1",
  "40:2",
  "34:3",
  "38:4",
  "41:7",
]
substitutions = [
  "23:7",
]
with_communication = false

[recording_intervals]
Control = 1
VisionTop = 30
VisionBottom = 30
SplNetwork = 1
# ObjectDetectionTop = 30
# Audio = 1
