opponent = "RoboEireann"
phase = "golden-goal"
location = "rc25"
wifi = "SPL_A"
base = "hulk/main"
branches = [
    "oleflb/keep-a-calm-head",
    "schluis/send-more-messages",
    "paudar/defender-searcher-delay",
    "vivi-enne/increase_kick_off_angle",
    "rmburg/loser-to-searcher",
    "franziska-sophie/field-color-fieldA",
    "paudar/dont_trust_teamballs",


]
assignments = [
    #
    "38:1",
    "34:2",
    "21:3",
    "32:4",
    "39:5",
]
substitutions = [
    #"41:6",
    #"40:7",
]
with_communication = false

[recording_intervals]
Control = 1
VisionTop = 30
VisionBottom = 30
SplNetwork = 1
# ObjectDetectionTop = 30
# Audio = 1
