opponent = "DutchNaoTeam"
phase = "second-half"
location = "rc25"
wifi = "SPL_A"
base = "hulk/main"
branches = [
    #
    "vivi-enne/defender_no_criss_cross",
    "vivi-enne/increase_kick_off_angle",
    "paudar/defender-searcher-delay",
    "schluis/eckiger-leuchtturm",
    "schmidma/dynamic-measurement-noise",
    "schmidma/standing-supporter",
    "rmburg/slower-head-motion-2",
    "paudar/update_odometry_2",
    "ThagonDuarte/2025-07-19-calibrations-dnt",
    "paudar/dont_trust_teamballs",
    "pejotejo/forward-kick-tuning",
    "oleflb/revert-filter-calib2",

]
assignments = [
    #
    "38:1",
    "34:2",
    "21:3",
    "39:4",
    "32:5",
]
substitutions = [
    #"41:6",
    #"40:7",
]
with_communication = false

[recording_intervals]
Control = 1
VisionTop = 30
VisionBottom = 30
SplNetwork = 1
# ObjectDetectionTop = 30
# Audio = 1
