opponent = "SPQR"
phase = "golden-goal"
location = "rc25"
wifi = "SPL_C"
base = "hulk/main"
branches = [
    "paudar/defender-searcher-delay",
    "vivi-enne/defender_no_criss_cross",
    "pejotejo/turn_kicks_tuning",
    "oleflb/calibrations-sqpr",
]
assignments = [
    #
    "37:1",
    "36:2",
    "33:3",
    "38:4",
    "41:5",
]
substitutions = [
    # "32:",
    # "21:",
]
with_communication = false

[recording_intervals]
Control = 1
VisionTop = 30
VisionBottom = 30
SplNetwork = 1
# ObjectDetectionTop = 30
# Audio = 1
