opponent = "WisTEX"
phase = "golden-goal"
location = "rc25"
wifi = "SPL_B"
base = "hulk/main"
branches = [
  "schmidma/multiple-datasets",
  "rmburg/mpc-step-planning",
  "ThagonDuarte/5v5-more-robors-doing-visual-referee",
  "schmidma/walking-parameter",
  "ThagonDuarte/2025-17-16-calibrations",
]
assignments = [
  #
  "37:1",
  "33:2",
  "35:3",
  "40:4",
  "38:5",
]
substitutions = [
  # ":",
  # ":",
]
with_communication = false

[recording_intervals]
Control = 1
VisionTop = 30
VisionBottom = 30
SplNetwork = 1
# ObjectDetectionTop = 30
# Audio = 1
