opponent = "SPQR"
phase = "second-half"
location = "rc25"
wifi = "SPL_C"
base = "hulk/main"
branches = [
    "paudar/defender-searcher-delay",
    "vivi-enne/defender_no_criss_cross",
    "pejotejo/turn_kicks_tuning",
    "oleflb/calibrations-sqpr",
    "schmidma/tune-walking",
]
assignments = [
    #
    "33:1",
    "38:2",
    "41:3",
    "32:4",
    "36:5",
]
substitutions = [
    # "32:1",
    # "21:1",
]
with_communication = false

[recording_intervals]
Control = 1
VisionTop = 30
VisionBottom = 30
SplNetwork = 1
# ObjectDetectionTop = 30
# Audio = 1
