opponent = "RoboEireann"
phase = "first-half"
location = "rc25"
wifi = "SPL_A"
base = "hulk/main"
branches = [
  # "schluis/tune-catching-steps",
]
assignments = [
  #
  "37:1",
  "33:2",
  "35:3",
  "40:4",
  "38:5",
]
substitutions = [
  # ":",
  # ":",
]
with_communication = true

[recording_intervals]
Control = 1
VisionTop = 30
VisionBottom = 30
SplNetwork = 1
# ObjectDetectionTop = 30
# Audio = 1
