opponent = "HTWK"
phase = "second-half"
location = "go25"
wifi = "SPL_A"
base = "hulk/main"
branches = [
  "oleflb/fix-kicking-team-filter",
  "oleflb/ball-filter-save-last-mode",
  "Franziska-Sophie/field-color-detection",
  "paudar/change-line_measurement_noise",
  "paudar/defender-searcher-delay",
  "schmidma/more-aggressive-defender",
  "schluis/penalty-shot-strength",
  "schmidma/parameters",
  "tuxbotix/16_morning_tuxbotix_40",
]
assignments = [
  "38:1",
  "21:2",
  "34:3",
  "32:4",
  "37:5",
  "33:6",
  "41:7",
]
substitutions = [
  # "30:",
  # "31:",
  "40:1",
]
with_communication = false

[recording_intervals]
Control = 1
VisionTop = 30
VisionBottom = 30
SplNetwork = 1
# ObjectDetectionTop = 30
# Audio = 1
