opponent = "NaoDevils"
phase = "golden-goal"
location = "rc25"
wifi = "SPL_C"
base = "hulk/main"
branches = [
  "rmburg/mpc-step-planning",
  "schmidma/no-zero-segments",
  "schmidma/balancing",
  "knoellle/ignore-team-balls",
  "vivi-enne/defender_no_criss_cross"
]
assignments = [
  #
  "32:1",
  "36:2",
  "33:3",
  "38:4",
  "41:5",
]
substitutions = [
  # "35:",
  # "21:",
]
with_communication = false

[recording_intervals]
Control = 1
VisionTop = 30
VisionBottom = 30
SplNetwork = 1
# ObjectDetectionTop = 30
# Audio = 1
