opponent = "Berlin_United"
phase = "second-half"
location = "go25"
wifi = "SPL_B"
base = "hulk/main"
branches = [
  "paudar/change-line_measurement_noise",
  "oleflb/ball-filter-save-last-mode",
  "paudar/defender-searcher-delay",
  "Franziska-Sophie/field-color-detection",
  "tuxbotix/15_evening",
]
assignments = [
  "38:1",
  "23:2",
  "34:3",
  "33:4",
  "32:5",
  "40:6",
  "41:7",
]
substitutions = [
  # "30:5",
  # "21:",
]
with_communication = false

[recording_intervals]
Control = 1
VisionTop = 30
VisionBottom = 30
SplNetwork = 1
# ObjectDetectionTop = 30
# Audio = 1
