player_number = "Three"

[rl_walking]
gait_frequency = 1
stabilizing_interval_completion_threshold = 0.01
stabilizing_interval_compression_factor = 1
number_of_actions = 12
number_of_observations = 47
walk_command = [0, 0, 0]
joint_position_smoothing_factor = 0.8

[rl_walking.torque_limits]
head = { yaw = 7, pitch = 7 }
left_arm = { shoulder_pitch = 10, shoulder_roll = 10, shoulder_yaw = 10, elbow = 10 }

[rl_walking.torque_limits.right_arm]
shoulder_pitch = 10
shoulder_roll = 10
shoulder_yaw = 10
elbow = 10

[rl_walking.torque_limits.left_leg]
hip_pitch = 60
hip_roll = 25
hip_yaw = 30
knee = 60
ankle_up = 24
ankle_down = 15

[rl_walking.torque_limits.right_leg]
hip_pitch = 60
hip_roll = 25
hip_yaw = 30
knee = 60
ankle_up = 24
ankle_down = 15

[rl_walking.normalization]
gravity = 1
linear_velocity = 1
angular_velocity = 1
joint_position = 1
joint_velocity = 0.1
clip_actions = 1

[rl_walking.control]
dt = 0.01
action_scale = 1
decimation = 10

[prepare_motor_command]
weight = 1

[prepare_motor_command.default_positions.head]
yaw = 0
pitch = 0

[prepare_motor_command.default_positions.left_arm]
shoulder_pitch = 0.2
shoulder_roll = -1.4
shoulder_yaw = 0
elbow = -0.5

[prepare_motor_command.default_positions.right_arm]
shoulder_pitch = 0.2
shoulder_roll = 1.4
shoulder_yaw = 0
elbow = 0.5

[prepare_motor_command.default_positions.left_leg]
hip_pitch = -0.2
hip_roll = 0
hip_yaw = 0
knee = 0.4
ankle_up = -0.175
ankle_down = 0

[prepare_motor_command.default_positions.right_leg]
hip_pitch = -0.2
hip_roll = 0
hip_yaw = 0
knee = 0.4
ankle_up = -0.175
ankle_down = 0

[prepare_motor_command.proportional_coefficients.head]
yaw = 10
pitch = 10

[prepare_motor_command.proportional_coefficients.left_arm]
shoulder_pitch = 10
shoulder_roll = 10
shoulder_yaw = 10
elbow = 10

[prepare_motor_command.proportional_coefficients.right_arm]
shoulder_pitch = 10
shoulder_roll = 10
shoulder_yaw = 10
elbow = 10

[prepare_motor_command.proportional_coefficients.left_leg]
hip_pitch = 140
hip_roll = 140
hip_yaw = 140
knee = 140
ankle_up = 50
ankle_down = 10

[prepare_motor_command.proportional_coefficients.right_leg]
hip_pitch = 140
hip_roll = 140
hip_yaw = 140
knee = 140
ankle_up = 50
ankle_down = 10

[prepare_motor_command.derivative_coefficients.head]
yaw = 1
pitch = 1

[prepare_motor_command.derivative_coefficients.left_arm]
shoulder_pitch = 1
shoulder_roll = 1
shoulder_yaw = 1
elbow = 1

[prepare_motor_command.derivative_coefficients.right_arm]
shoulder_pitch = 1
shoulder_roll = 1
shoulder_yaw = 1
elbow = 1

[prepare_motor_command.derivative_coefficients.left_leg]
hip_pitch = 3.5
hip_roll = 3.5
hip_yaw = 3.5
knee = 3.5
ankle_up = 1.5
ankle_down = 1

[prepare_motor_command.derivative_coefficients.right_leg]
hip_pitch = 3.5
hip_roll = 3.5
hip_yaw = 3.5
knee = 3.5
ankle_up = 1.5
ankle_down = 1

[common_motor_command]
weight = 1

[common_motor_command.default_positions.head]
yaw = 0
pitch = 0.4

[common_motor_command.default_positions.left_arm]
shoulder_pitch = 0.2
shoulder_roll = -1.35
shoulder_yaw = 0
elbow = -0.5

[common_motor_command.default_positions.right_arm]
shoulder_pitch = 0.2
shoulder_roll = 1.35
shoulder_yaw = 0
elbow = 0.5

[common_motor_command.default_positions.left_leg]
hip_pitch = -0.2
hip_roll = 0
hip_yaw = 0
knee = 0.4
ankle_up = -0.25
ankle_down = 0

[common_motor_command.default_positions.right_leg]
hip_pitch = -0.2
hip_roll = 0
hip_yaw = 0
knee = 0.4
ankle_up = -0.25
ankle_down = 0

[common_motor_command.proportional_coefficients.head]
yaw = 10
pitch = 10

[common_motor_command.proportional_coefficients.left_arm]
shoulder_pitch = 10
shoulder_roll = 10
shoulder_yaw = 10
elbow = 10

[common_motor_command.proportional_coefficients.right_arm]
shoulder_pitch = 10
shoulder_roll = 10
shoulder_yaw = 10
elbow = 10

[common_motor_command.proportional_coefficients.left_leg]
hip_pitch = 140
hip_roll = 140
hip_yaw = 140
knee = 140
ankle_up = 35
ankle_down = 10

[common_motor_command.proportional_coefficients.right_leg]
hip_pitch = 140
hip_roll = 140
hip_yaw = 140
knee = 140
ankle_up = 35
ankle_down = 10

[common_motor_command.derivative_coefficients.head]
yaw = 0.5
pitch = 0.5

[common_motor_command.derivative_coefficients.left_arm]
shoulder_pitch = 0.2
shoulder_roll = 0.2
shoulder_yaw = 0.2
elbow = 0.2

[common_motor_command.derivative_coefficients.right_arm]
shoulder_pitch = 0.2
shoulder_roll = 0.2
shoulder_yaw = 0.2
elbow = 0.2

[common_motor_command.derivative_coefficients.left_leg]
hip_pitch = 3.5
hip_roll = 3.5
hip_yaw = 3.5
knee = 3.5
ankle_up = 1.5
ankle_down = 1

[common_motor_command.derivative_coefficients.right_leg]
hip_pitch = 3.5
hip_roll = 3.5
hip_yaw = 3.5
knee = 3.5
ankle_up = 1.5
ankle_down = 1

[remote_control_parameters.walk]
forward = 0
left = 0
turn = 0

[game_controller_filter.time_since_last_message_to_consider_ip_active]
nanos = 0
secs = 5

[game_controller_filter.collision_alert_cooldown]
nanos = 0
secs = 10

[game_state_filter]
distance_to_consider_ball_moved_in_kick_off = 0.3
whistle_acceptance_goal_distance = [0.5, 0.5]

[game_state_filter.game_controller_controller_delay]
nanos = 0
secs = 3

[game_state_filter.playing_message_delay]
nanos = 0
secs = 15

[game_state_filter.ready_message_delay]
nanos = 0
secs = 15

[game_state_filter.kick_off_grace_period]
nanos = 0
secs = 10

[game_state_filter.tentative_finish_duration]
nanos = 0
secs = 4

[game_state_filter.duration_to_keep_observed_ball]
nanos = 0
secs = 14

[game_state_filter.duration_to_keep_new_penalties]
nanos = 0
secs = 30

[field_dimensions]
ball_radius = 0.095
length = 9
width = 6
line_width = 0.05
penalty_marker_size = 0.1
goal_box_area_length = 0.6
goal_box_area_width = 2.2
penalty_area_length = 1.65
penalty_area_width = 4
penalty_marker_distance = 1.3
center_circle_diameter = 1.5
border_strip_width = 2
goal_inner_width = 1.5
goal_post_diameter = 0.1
goal_depth = 0.5

[object_detection]
enable = true
maximum_intersection_over_union = 0.7
confidence_threshold = 0.5

[ball_projection]
detection_noise = [8, 8]

[camera_matrix_parameters]
camera_to_head_pitch = -0.2125811028
correction_in_robot = [0, 0, 0]
correction_in_camera = [0, 0, 0]

[cycler_frequencies]
world_state = 100
