#!/bin/bash

set -e

THIS_DIRECTORY="$(dirname $(readlink -f $0))"
PEPSI_TARGET_DIRECTORY=${CARGO_TARGET_DIR:-${THIS_DIRECTORY}/tools/pepsi/target}

cargo build --release --manifest-path="${THIS_DIRECTORY}/tools/pepsi/Cargo.toml"
# cargo sets LD_LIBRARY_PATH which we don't want, so let's call the binary directly
"${PEPSI_TARGET_DIRECTORY}/release/pepsi" "$@"
