from absl.testing import parameterized

class MuJoCoRendererTest(parameterized.TestCase):
    def test_renderer_unknown_camera_name(self) -> None: ...
    def test_renderer_camera_under_range(self) -> None: ...
    def test_renderer_camera_over_range(self) -> None: ...
    def test_renderer_renders_scene(self) -> None: ...
    def test_renderer_output_without_out(self) -> None: ...
    def test_renderer_output_with_out(self) -> None: ...
