[project]
name = "walking-engine"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
  "common-types",
  "kinematics",
  "numpy>=1.2.0",
  "robot-dimensions",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
