[project]
name = "walking-engine"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = ["numpy"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
