[project]
name = "transforms"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = ["numpy>=1.2.0", "scipy>=1.14.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
