[project]
name = "transforms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy", "scipy"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
