use super::super::prelude::*;
use super::synthetic::SyntheticFrame;

pub(in super::super) fn assert_candidate_matches_truth(
    candidate: &Candidate,
    problem: &Problem,
    frame: &SyntheticFrame,
) -> Result<(), String> {
    for accepted in &candidate.matches {
        let detection = problem
            .detections
            .get(accepted.detection_index)
            .ok_or_else(|| format!("missing detection index {}", accepted.detection_index))?;
        let truth_id = frame
            .truth_by_detection_id
            .get(detection.id)
            .ok_or_else(|| {
                format!(
                    "detection id {} was not generated by the synthetic frame",
                    detection.id
                )
            })?;
        if accepted.landmark_id != *truth_id {
            return Err(format!(
                "detection {} resolved to landmark {}, expected {}",
                detection.id, accepted.landmark_id, truth_id
            ));
        }
    }
    Ok(())
}

pub(in super::super) fn assert_no_incorrect_associations(
    result: &GlobalLocalizationResult,
    frame: &SyntheticFrame,
    map: &LandmarkMap,
    case_name: &str,
) -> Result<(), String> {
    assert_feature_associations_have_truth(
        &result.associations().features,
        frame,
        map,
        0,
        case_name,
    )
}

pub(in super::super) fn assert_feature_associations_have_truth(
    associations: &[FeatureAssociation],
    frame: &SyntheticFrame,
    map: &LandmarkMap,
    case_index: usize,
    status: &str,
) -> Result<(), String> {
    for association in associations {
        let Some(&truth_id) = frame.truth_by_detection_id.get(association.detection_id) else {
            return Err(format!(
                "{status} case {case_index}: detection id {} was not generated by the synthetic frame",
                association.detection_id
            ));
        };
        if association.landmark_id != truth_id
            && association.landmark_id != map.symmetric_id(truth_id)
        {
            let expected = &map.landmarks[truth_id];
            let expected_symmetric = &map.landmarks[map.symmetric_id(truth_id)];
            let actual = &map.landmarks[association.landmark_id];
            return Err(format!(
                "{status} case {case_index}: detection {} associated with landmark {} {:?} at ({:.3}, {:.3}), expected {} or symmetric {} at ({:.3}, {:.3}) / ({:.3}, {:.3})",
                association.detection_id,
                association.landmark_id,
                actual.class,
                actual.xy.x(),
                actual.xy.y(),
                truth_id,
                expected_symmetric.id,
                expected.xy.x(),
                expected.xy.y(),
                expected_symmetric.xy.x(),
                expected_symmetric.xy.y()
            ));
        }
    }
    Ok(())
}
