use super::super::prelude::*;
use super::synthetic::SyntheticFrame;

pub(in super::super) fn candidate(matches: Vec<(usize, usize, VisualFeatureClass)>) -> Candidate {
    let matches = matches
        .into_iter()
        .map(|(detection_index, landmark_id, class)| Match {
            detection_index,
            landmark_id,
            class,
            confidence: 0.9,
            residual: 0.0,
        })
        .collect::<Vec<_>>();
    Candidate {
        score: matches.len() as f32,
        matches,
        metric_rms_residual: 0.0,
        transform: Similarity2::new(Vector2::zeros(), 0.0, 0.5),
    }
}

pub(in super::super) fn candidate_from_problem_truth(
    problem: &Problem,
    frame: &SyntheticFrame,
    map: &LandmarkMap,
    symmetric: bool,
) -> Result<Candidate, String> {
    problem
        .detections
        .iter()
        .enumerate()
        .map(|(detection_index, detection)| {
            let truth_id = *frame
                .truth_by_detection_id
                .get(detection.id)
                .ok_or_else(|| {
                    format!(
                        "detection id {} was not generated by the synthetic frame",
                        detection.id
                    )
                })?;
            let landmark_id = if symmetric {
                map.symmetric_id(truth_id)
            } else {
                truth_id
            };
            Ok((detection_index, landmark_id, detection.class))
        })
        .collect::<Result<Vec<_>, _>>()
        .map(candidate)
}
