mod audio_spectrum;
mod behavior_simulator;
mod enum_plot;
mod image;
mod image_color_select;
mod image_segments;
mod look_at;
mod map;
mod mujoco_simulator;
mod parameter;
mod plot;
mod remote_control;
mod text;
mod vision_tuner;

pub use audio_spectrum::AudioSpectrumPanel;
pub use behavior_simulator::BehaviorSimulatorPanel;
pub use enum_plot::EnumPlotPanel;
pub use image::ImagePanel;
pub use image_color_select::ImageColorSelectPanel;
pub use image_segments::ImageSegmentsPanel;
pub use look_at::LookAtPanel;
pub use map::MapPanel;
pub use mujoco_simulator::MujocoSimulatorPanel;
pub use parameter::ParameterPanel;
pub use plot::PlotPanel;
pub use remote_control::RemotePanel;
pub use text::TextPanel;
pub use vision_tuner::VisionTunerPanel;
