[project]
version = "0.1.0"
name = "mujoco-interactive-viewer"
requires-python = ">=3.10"
dependencies = ["glfw>=2.8.0", "mujoco>=3.2.6", "numpy>=1.26.4"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
