[project]
name = "nao-interface"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = ["mujoco"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
