[package]
name = "step_planning_solver"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
color-eyre.workspace = true
coordinate_systems.workspace = true
geometry.workspace = true
linear_algebra.workspace = true
nalgebra.workspace = true
num-dual.workspace = true
optimization_engine.workspace = true
step_planning.workspace = true
types.workspace = true

[dev-dependencies]
criterion = { version = "0.5" }

[[bench]]
name = "mpc_step_planning"
harness = false
