[package]
name = "hula"
version = "0.5.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[dependencies]
clap = { workspace = true }
color-eyre = { workspace = true }
constants = { workspace = true }
env_logger = { workspace = true }
epoll = { workspace = true }
hula-types = { workspace = true }
log = { workspace = true }
rmp-serde = { workspace = true }
systemd = { workspace = true }
zbus = { workspace = true }
