[package]
name = "hula"
version = "0.4.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[dependencies]
chrono = "0.4.23"
clap = { version = "4.0.29", features = ["derive"] }
color-eyre = "0.6.2"
constants = { path = "../../../crates/constants" }
env_logger = "0.10.0"
epoll = "4.3.1"
hula-types = { path = "../types/" }
log = "0.4.17"
rmp-serde = "1.1.1"
systemd = "0.10.0"
zbus = { workspace = true }
