[project]
name = "fall-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ai-edge-litert>=1.3.0",
    "click>=8.2.1",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "mcap>=1.2.2",
    "msgpack>=1.1.1",
    "polars>=1.30.0",
    "pyqt6>=6.9.1",
    "scipy>=1.15.3",
    "seaborn>=0.13.2",
    "tensorflow>=2.19.0",
    "tqdm>=4.67.1",
]
