[project]
name = "fall-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ai-edge-litert>=1.3.0",
    "click>=8.2.1",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "mcap>=1.2.2",
    "msgpack>=1.1.1",
    "nbformat>=5.10.4",
    "pandas>=2.3.0",
    "plotly>=6.0.1",
    "polars>=1.26.0",
    "pyarrow>=20.0.0",
    "pyqt6>=6.9.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "seaborn>=0.13.2",
    "tensorflow>=2.19.0",
    "tqdm>=4.67.1",
    "wandb>=0.21.0",
]

[dependency-groups]
dev = ["ruff>=0.11.2"]
