[package]
name = "localizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
bincode = { workspace = true }
clap = { workspace = true, features = ["derive"] }
control = { workspace = true }
serde = { workspace = true }
