[package]
name = "localizer"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { workspace = true }
clap = { workspace = true, features = ["derive"] }
color-eyre = { workspace = true }
communication = { workspace = true, features = ["server"] }
control = { workspace = true }
framework = { workspace = true }
linear_algebra = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
serialize_hierarchy = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
types = { workspace = true }
