[package]
name = "hungarian_algorithm"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { workspace = true }
ordered-float = { workspace = true }
pathfinding = { workspace = true }
