pub enum Action {
    Unstiff,
    SitDown,
    Penalize,
    FallSafely,
    StandUp,
    Stand,

    LookAround,
    Dribble,
    DefendGoal,
    DefendKickOff,
    DefendLeft,
    DefendRight,
    DefendPenaltyKick,
    Jump,
    PrepareJump,
    SupportLeft,
    SupportRight,
    SupportStriker,
    Search,
    SearchForLostBall,
    WalkToKickOff,
    WalkToPenaltyKick,
}
