[package]
name = "coordinate_systems"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[dependencies]
nalgebra = { workspace = true }
serde = { workspace = true }
serialize_hierarchy = { workspace = true }
approx = { workspace = true }
