#!/bin/bash

rm -rf ctc-hulks-clang
rm -rf tools x-tools libs
rm -rf ctc-linux*
rm -rf sysroot*
rm -rf ctc-hulks-config/.build
rm -rf ctc-hulks-config/config.gen
rm -f ctc-hulks-config/.config.old
rm -f ctc-hulks-config/build.log
rm -f ctc-hulks-config/config
