#!/bin/bash

# Get base directory for better referencing
BASEDIR=`cd $(dirname $0); pwd -P`
CT_INSTALL=${BASEDIR}/tools/ct-ng

echo "++++++++ Setting up folders ++++++++"
cd ${BASEDIR}
mkdir -p tools
mkdir -p x-tools
mkdir -p libs
mkdir -p tarballs

# Source files
source versions
source functions
source env.sh

echo ""
echo "++++++++ Install crosstool-ng ++++++++"
cd tools
git clone https://github.com/crosstool-ng/crosstool-ng.git
cd crosstool-ng
git checkout ${CROSSTOOL_VERSION}
git apply ${BASEDIR}/patches/crosstool-ng/3f461da1/silvermont-i686.patch

# Make the ARCH compile to a i686 toolchain
set -e
./bootstrap
./configure --prefix=${CT_INSTALL}
make
make install

# Prepare the crosstool-ng toolchain environment
cd ${BASEDIR}
cd ctc-hulks-config
ct-ng oldconfig
