#!/bin/bash

# Get base directory for better referencing
BASEDIR=`cd $(dirname $0); pwd -P`
CLANG_BASEDIR=${BASEDIR}/ctc-hulks-clang

echo ${BASEDIR}
cd ${BASEDIR}
source env.sh

cd ctc-hulks-config
BASEDIR=${BASEDIR} ct-ng build

# Configure project
gcc_version=`${BASEDIR}/x-tools/i686-nao-linux-gnu/bin/i686-nao-linux-gnu-gcc -dumpversion`
cd ${CLANG_BASEDIR}
rm -rf llvm-build
mkdir llvm-build
cd llvm-build
cmake \
  -G "Ninja" \
  -DCMAKE_INSTALL_PREFIX=${CLANG_BASEDIR}/llvm-inst \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_TARGETS_TO_BUILD="X86" \
  -DLLVM_BINUTILS_INCDIR=${BASEDIR}/x-tools/i686-nao-linux-gnu/lib/gcc/i686-nao-linux-gnu/${gcc_version}/plugin/include \
  -DLLVM_ENABLE_TERMINFO=OFF \
  ${CLANG_BASEDIR}/llvm
ninja -j$((`nproc` + 1)) install

