[package]
name = "energy_optimization"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[dependencies]
serde = { workspace = true }
serialize_hierarchy = { workspace = true }
types = { workspace = true }
