[package]
name = "energy_optimization"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
serde = { workspace = true }
serialize_hierarchy = { workspace = true }
types = { workspace = true }
