[package]
name = "kinematics"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
linear_algebra = { workspace = true }
nalgebra = { workspace = true }
types = { workspace = true }
