[project]
name = "object-detection"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"

dependencies = [
  "click>=8.1.7",
  "huggingface-hub>=0.29.1",
  "openvino==2024.6.0",
  "ultralytics",
]
