[project]
name = "object-detection"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"

dependencies = [
  "click>=8.1.7",
  "onnx==1.17.0",
  "openvino==2025.0.0",
  "ultralytics>=8.3.75",
]

[tool.uv]
dev-dependencies = [
  "neovim>=0.3.1",
  "pyright>=1.1.392.post0",
  "pytest>=8.3.3",
  "ruff>=0.7.3",
]
