[project]
name = "nao-env"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"

dependencies = ["gymnasium", "nao_interface", "numpy", "rewards", "throwing"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
