#!/usr/bin/env bash

CURRENT_DATE=$(date +%s)
INTERNAL_LOG_PATH=/home/nao/naoqi
EXTERNAL_LOG_PATH=$(grep -m1 '^/dev/sda1' /proc/mounts | cut -d ' ' -f 2)/logs

mkdir -p ${EXTERNAL_LOG_PATH}

(
  cd ${INTERNAL_LOG_PATH};
  ln -sf ${INTERNAL_LOG_PATH}/hulk-${CURRENT_DATE}.out hulk.out;
  ln -sf ${INTERNAL_LOG_PATH}/hulk-${CURRENT_DATE}.err hulk.err
)

/home/nao/naoqi/bin/hulk \
         > >(tee ${EXTERNAL_LOG_PATH}/hulk-${CURRENT_DATE}.out > ${INTERNAL_LOG_PATH}/hulk-${CURRENT_DATE}.out) \
        2> >(tee ${EXTERNAL_LOG_PATH}/hulk-${CURRENT_DATE}.err > ${INTERNAL_LOG_PATH}/hulk-${CURRENT_DATE}.err)
