[package]
name = "checky"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
ariadne = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
itertools = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true }
walkdir = { workspace = true }
