team_number = 24

[[robots]]
number = 42
hostname = "Ernst-Guenther"
id = "1421625075354"

[[robots]]
number = 43
hostname = "Ute"
id = "1422125017018"

[[robots]]
number = 44
hostname = "Anton"
id = "1421625074001"

[[robots]]
number = 45
hostname = "Berta"
id = "1421625075359"
