[package]
name = "motion_inference"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
booster.workspace = true
color-eyre.workspace = true
coordinate_systems.workspace = true
kinematics.workspace = true
linear_algebra.workspace = true
nalgebra.workspace = true
ort = { workspace = true, features = ["load-dynamic"] }
ros-z.workspace = true
ros-z-schema.workspace = true
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "time"] }
types.workspace = true
