[package]
edition = "2021"
name = "camera_matrix_extractor"
version = "0.1.0"

[dependencies]
color-eyre = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
structopt = { workspace = true }
