[[cyclers]]
name = "Control"
kind = "RealTime"
setup_nodes = []
nodes = [
  "control::active_vision",
  "control::ball_filter",
  "control::ball_state_composer",
  "control::behavior::node",
  "control::fall_state_estimation",
  "control::game_controller_filter",
  "control::game_state_filter",
  "control::ground_contact_detector",
  "control::hulk_message_filter",
  "control::kick_selector",
  "control::localization",
  "control::obstacle_filter",
  "control::penalty_shot_direction_estimation",
  "control::primary_state_filter",
  "control::role_assignment",
  "control::rule_obstacle_composer",
  "control::sensor_data_receiver",
  "control::world_state_composer",
]

