[[cyclers]]
name = "Control"
kind = "RealTime"
setup_nodes = []
nodes = [
  { module = "crate::fake_data", path= "../tools/behavior_simulator/src/fake_data.rs" },
  "control::active_vision",
  "control::ball_state_composer",
  "control::behavior::node",
  "control::kick_selector",
  "control::role_assignment",
  "control::rule_obstacle_composer",
  "control::world_state_composer",
]

