[package]
name = "constants"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
lazy_static = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}