[package]
edition = "2021"
license = "GPL-3.0-only"
name = "spl_network2"
version = "0.1.0"

[dependencies]
anyhow = "1.0.59"
context_attribute = {path = "../context_attribute"}

# convert_case = "0.5.0"
# module_attributes2 = {path = "../module_attributes2"}
# petgraph = "0.6.2"
# proc-macro2 = {version = "1.0.39", features = ["span-locations"]}
# syn = {version = "1.0.82", features = ["full"]}
# walkdir = "2.3.2"
