from __future__ import annotations
import typing
__all__ = ['get_mjcb_act_bias', 'get_mjcb_act_dyn', 'get_mjcb_act_gain', 'get_mjcb_contactfilter', 'get_mjcb_control', 'get_mjcb_passive', 'get_mjcb_sensor', 'get_mjcb_time', 'get_mju_user_free', 'get_mju_user_malloc', 'get_mju_user_warning', 'set_mjcb_act_bias', 'set_mjcb_act_dyn', 'set_mjcb_act_gain', 'set_mjcb_contactfilter', 'set_mjcb_control', 'set_mjcb_passive', 'set_mjcb_sensor', 'set_mjcb_time', 'set_mju_user_free', 'set_mju_user_malloc', 'set_mju_user_warning']
def get_mjcb_act_bias() -> typing.Any:
    ...
def get_mjcb_act_dyn() -> typing.Any:
    ...
def get_mjcb_act_gain() -> typing.Any:
    ...
def get_mjcb_contactfilter() -> typing.Any:
    ...
def get_mjcb_control() -> typing.Any:
    ...
def get_mjcb_passive() -> typing.Any:
    ...
def get_mjcb_sensor() -> typing.Any:
    ...
def get_mjcb_time() -> typing.Any:
    ...
def get_mju_user_free() -> typing.Any:
    ...
def get_mju_user_malloc() -> typing.Any:
    ...
def get_mju_user_warning() -> typing.Any:
    ...
def set_mjcb_act_bias(arg0: typing.Any) -> None:
    ...
def set_mjcb_act_dyn(arg0: typing.Any) -> None:
    ...
def set_mjcb_act_gain(arg0: typing.Any) -> None:
    ...
def set_mjcb_contactfilter(arg0: typing.Any) -> None:
    ...
def set_mjcb_control(arg0: typing.Any) -> None:
    ...
def set_mjcb_passive(arg0: typing.Any) -> None:
    ...
def set_mjcb_sensor(arg0: typing.Any) -> None:
    ...
def set_mjcb_time(arg0: typing.Any) -> None:
    ...
def set_mju_user_free(arg0: typing.Any) -> None:
    ...
def set_mju_user_malloc(arg0: typing.Any) -> None:
    ...
def set_mju_user_warning(arg0: typing.Any) -> None:
    ...
