from _typeshed import Incomplete
from absl.testing import parameterized
from collections.abc import Generator

TEST_XML: str
TEST_XML_SENSOR: str
TEST_XML_PLUGIN: str
TEST_XML_TEXTURE: str

def temporary_callback(setter, callback) -> Generator[None]: ...

class MuJoCoBindingsTest(parameterized.TestCase):
    model: Incomplete
    data: Incomplete
    def setUp(self) -> None: ...
    def test_load_xml_can_handle_name_clash(self) -> None: ...
    def test_load_xml_repeated_asset_name(self) -> None: ...
    def test_can_read_array(self) -> None: ...
    def test_can_set_array(self) -> None: ...
    def test_array_is_a_view(self) -> None: ...
    def test_array_keeps_struct_alive(self) -> None: ...
    def test_named_indexing_actuator_ctrl(self) -> None: ...
    def test_named_indexing_invalid_names_in_model(self) -> None: ...
    def test_named_indexing_no_name_argument_in_model(self) -> None: ...
    def test_named_indexing_invalid_names_in_data(self) -> None: ...
    def test_named_indexing_no_name_argument_in_data(self) -> None: ...
    def test_named_indexing_invalid_index_in_model(self) -> None: ...
    def test_named_indexing_invalid_index_in_data(self) -> None: ...
    def test_named_indexing_geom_size(self) -> None: ...
    def test_named_indexing_geom_quat(self) -> None: ...
    def test_named_indexing_ragged_qpos(self) -> None: ...
    def test_named_indexing_ragged2d_cdof(self) -> None: ...
    def test_named_indexing_repr_in_data(self) -> None: ...
    def test_named_indexing_body_repr_in_data(self) -> None: ...
    def test_named_indexing_repr_in_model(self) -> None: ...
    def test_addresses_differ_between_structs(self) -> None: ...
    def test_mjmodel_can_read_and_write_opt(self) -> None: ...
    def test_mjmodel_can_read_and_write_stat(self) -> None: ...
    def test_mjmodel_can_read_and_write_vis(self) -> None: ...
    def test_mjmodel_can_access_names_directly(self) -> None: ...
    def test_mjmodel_names_doesnt_copy(self) -> None: ...
    def test_vis_global_exposed_as_global_(self) -> None: ...
    def test_mjoption_can_make_default(self) -> None: ...
    def test_mjoption_can_copy(self) -> None: ...
    def test_mjmodel_can_copy(self) -> None: ...
    def test_mjdata_can_copy(self) -> None: ...
    def test_mjdata_can_read_warning_array(self) -> None: ...
    def test_mjcontact_can_copy(self): ...
    def test_mj_step(self): ...
    def test_mj_step_multiple(self) -> None: ...
    def test_mj_contact_list(self) -> None: ...
    def test_realloc_con_efc(self) -> None: ...
    def test_mj_struct_list_equality(self) -> None: ...
    def test_mj_struct_equality(self, cls, attr) -> None: ...
    def test_mj_struct_equality_array(self) -> None: ...
    def test_mj_struct_repr(self, cls, attr) -> None: ...
    def test_mj_struct_repr_for_subclass(self): ...
    def test_mju_rotVecQuat(self) -> None: ...
    def test_getsetstate(self) -> None: ...
    def test_mj_setKeyframe(self) -> None: ...
    def test_mj_angmomMat(self) -> None: ...
    def test_mj_jacSite(self) -> None: ...
    def test_docstrings(self) -> None: ...
    def test_float_constant(self) -> None: ...
    def test_string_constants(self) -> None: ...
    def test_enum_values(self) -> None: ...
    def test_enum_from_int(self) -> None: ...
    def test_enum_as_index(self) -> None: ...
    def test_enum_ops(self) -> None: ...
    def test_can_raise_error(self) -> None: ...
    count: int
    def test_mjcb_time(self): ...
    def test_mjcb_time_exception(self) -> None: ...
    def test_mjcb_time_wrong_return_type(self): ...
    def test_mjcb_time_not_callable(self) -> None: ...
    test: Incomplete
    expected_model: Incomplete
    expected_data: Incomplete
    def test_mjcb_sensor(self) -> None: ...
    def test_mjcb_control_not_leak_memory(self) -> None: ...
    def test_mjdata_holds_ref_to_model(self) -> None: ...
    def test_can_initialize_mjv_structs(self) -> None: ...
    def test_mjv_camera(self) -> None: ...
    def test_mjv_scene(self) -> None: ...
    def test_mjv_scene_without_model(self) -> None: ...
    def test_mj_ray(self) -> None: ...
    def test_mj_multi_ray(self) -> None: ...
    def test_inverse_fd_none(self) -> None: ...
    def test_geom_distance(self) -> None: ...
    def test_inverse_fd(self) -> None: ...
    def test_mjd_sub_quat(self) -> None: ...
    def test_mjd_quat_intergrate(self) -> None: ...
    def test_banded(self) -> None: ...
    def test_mju_box_qp(self) -> None: ...
    def test_mju_fill(self) -> None: ...
    def test_mju_eye(self) -> None: ...
    def test_mju_symmetrize(self) -> None: ...
    def test_mju_clip(self) -> None: ...
    def test_mju_mul_vec_mat_vec(self) -> None: ...
    def test_mju_dense_to_sparse(self) -> None: ...
    def test_mju_sparse_to_dense(self) -> None: ...
    def test_mju_euler_to_quat(self) -> None: ...
    def test_mj_printSchema(self, flg_html, flg_pad) -> None: ...
    def test_pickle_mjdata_clean(self) -> None: ...
    def test_pickle_mjdata(self) -> None: ...
    def test_pickle_mjdata_sparse(self) -> None: ...
    def test_pickle_mjmodel(self) -> None: ...
    def test_indexer_name_id(self) -> None: ...
    def test_load_plugin(self) -> None: ...
    def test_copy_mjdata_with_plugin(self) -> None: ...
    def test_deepcopy_mjdata_with_plugin(self) -> None: ...
    def test_texture_size(self) -> None: ...
