# /etc/skel/.bash_profile

export PATH="$PATH:/home/nao/bin:/home/nao/naoqi/bin"

# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
[[ -f ~/.bashrc ]] && . ~/.bashrc
