[package]
name = "motionfile"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
color-eyre = { workspace = true }
enum_dispatch = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
splines ={ workspace = true }
thiserror = { workspace = true }
types = { workspace = true }
