FROM docker.io/rust:1.92.0

RUN apt-get update && apt-get install --no-install-recommends --yes \
    buildah \
    clang \
    cmake \
    git-lfs \
    libasound2-dev \
    libdbus-1-dev \
    libhdf5-dev \
    libluajit-5.1-dev \
    libopusfile-dev \
    libpython3.13 \
    libsystemd-dev \
    libudev-dev \
    lua-inspect \
    ninja-build \
    python3 \
    python3-click \
    python3-git \
    podman \
    rsync \
    zstd \
    && rm --recursive --force /var/lib/apt/lists/*

RUN rustup component add clippy rustfmt

RUN useradd -u 1000 hulk
RUN usermod --add-subuids 10000-75535 hulk
RUN usermod --add-subgids 10000-75535 hulk
RUN podman system migrate

RUN --mount=type=cache,target=/cargo_home \
    CARGO_HOME=/cargo_home cargo install --locked taplo-cli --root /usr/local
