[package]
name = "annotato"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
clap = { workspace = true}
color-eyre = { workspace = true}
eframe = { workspace = true}
egui_extras = { workspace = true}
egui_plot = { workspace = true}
glob = { workspace = true}
image = { workspace = true}
once_cell = { workspace = true}
reqwest = { workspace = true}
serde = { workspace = true}
serde_json = { workspace = true}
toml = { workspace = true }
