[package]
name = "annotato"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true}
color-eyre = { workspace = true}
eframe = { workspace = true}
egui_extras = { workspace = true}
egui_plot = { workspace = true}
glob = { workspace = true}
image = { workspace = true}
serde = { workspace = true}
serde_json = { workspace = true}
