[package]
name = "label-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
color-eyre = "0.6.2"
eframe = "0.24.0"
egui_extras = { version = "0.24.0", features = ["image"] }
egui_plot = "0.24.0"
glob = "0.3.1"
image = { version = "0.24.7", features = ["png"] }
ndarray = "0.15.6"
ort = "1.16.2"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
