[project]
version = "0.1.0"
name = "rewards"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = ["nao-interface", "numpy>=1.2.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
