[project]
version = "0.1.0"
name = "rewards"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
  "mujoco>=3.2.6",
  "nao-interface",
  "numpy>=1.2.0",
  "walking-engine",
  "wandb>=0.19.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
