[package]
name = "path_serde"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
nalgebra = { workspace = true }
serde = { workspace = true }
path_serde_derive = { workspace = true }
thiserror = { workspace = true }
