[project]
name = "field-color-detection"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "click>=8.2.1",
  "joblib>=1.5.1",
  "lightgbm>=4.6.0",
  "scikit-learn>=1.7.0",
]

[tool.pyright]
typeCheckingMode = "standard"
