[project]
name = "field-color-detection"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "click>=8.2.1",
  "h5py>=3.14.0",
  "joblib>=1.5.1",
  "lightgbm>=4.6.0",
  "matplotlib>=3.10.3",
  "numba>=0.61.2",
  "numpy>=2.2.6",
  "opencv-python>=4.12.0.88",
  "optuna-dashboard>=0.19.0",
  "optuna>=4.4.0",
  "pandas>=2.3.1",
  "plotly>=6.2.0",
  "psutil>=7.0.0",
  "scikit-image>=0.25.2",
  "scikit-learn>=1.7.0",
]

[tool.pyright]
typeCheckingMode = "standard"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
