[project]
name = "field-color-detection"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "opencv-python>=4.11.0.86",
    "optuna>=4.2.1",
    "optunahub>=0.2.0",
    "pyqt6>=6.8.1",
    "scikit-learn>=1.6.1",
]
