[package]
name = "hula"
version = "0.5.0"
edition = "2021"
license = "GPL-3.0-only"
homepage = "https://github.com/hulks/hulk"

[package.metadata.pepsi]
cross-compile = true

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.29", features = ["derive"] }
color-eyre = "0.6.3"
env_logger = "0.11.6"
epoll = "4.3.3"
hula_types = { path = "../../crates/hula_types/" }
log = "0.4.25"
rmp-serde = "1.3.0"
serde = { version = "1.0.217", features = ["derive"] }
systemd = "0.10.0"
zbus = "5.5.0"
