use color_eyre::Result;
use path_serde::{PathDeserialize, PathIntrospect, PathSerialize};
use serde::{Deserialize, Serialize};

use crate::bounding_box::BoundingBox;

#[derive(
    Debug, Clone, Copy, Serialize, Deserialize, PathIntrospect, PathSerialize, PathDeserialize,
)]
pub struct Object<T> {
    pub label: T,
    pub bounding_box: BoundingBox,
}

#[derive(
    Debug,
    Clone,
    Copy,
    Serialize,
    Deserialize,
    PathIntrospect,
    PathSerialize,
    PathDeserialize,
    PartialEq,
)]
pub enum YOLOObjectLabel {
    Person = 0,
    Bicycle = 1,
    Car = 2,
    Motorcycle = 3,
    Airplane = 4,
    Bus = 5,
    Train = 6,
    Truck = 7,
    Boat = 8,
    Trafficlight = 9,
    Firehydrant = 10,
    Stopsign = 11,
    Parkingmeter = 12,
    Bench = 13,
    Bird = 14,
    Cat = 15,
    Dog = 16,
    Horse = 17,
    Sheep = 18,
    Cow = 19,
    Elephant = 20,
    Bear = 21,
    Zebra = 22,
    Giraffe = 23,
    Backpack = 24,
    Umbrella = 25,
    Handbag = 26,
    Tie = 27,
    Suitcase = 28,
    Frisbee = 29,
    Skis = 30,
    Snowboard = 31,
    Sportsball = 32,
    Kite = 33,
    Baseballbat = 34,
    Baseballglove = 35,
    Skateboard = 36,
    Surfboard = 37,
    Tennisracket = 38,
    Bottle = 39,
    Wineglass = 40,
    Cup = 41,
    Fork = 42,
    Knife = 43,
    Spoon = 44,
    Bowl = 45,
    Banana = 46,
    Apple = 47,
    Sandwich = 48,
    Orange = 49,
    Broccoli = 50,
    Carrot = 51,
    Hotdog = 52,
    Pizza = 53,
    Donut = 54,
    Cake = 55,
    Chair = 56,
    Couch = 57,
    Pottedplant = 58,
    Bed = 59,
    Diningtable = 60,
    Toilet = 61,
    Tv = 62,
    Laptop = 63,
    Mouse = 64,
    Remote = 65,
    Keyboard = 66,
    Cellphone = 67,
    Microwave = 68,
    Oven = 69,
    Toaster = 70,
    Sink = 71,
    Refrigerator = 72,
    Book = 73,
    Clock = 74,
    Vase = 75,
    Scissors = 76,
    Teddybear = 77,
    Hairdrier = 78,
    Toothbrush = 79,
}

impl YOLOObjectLabel {
    pub fn from_index(index: usize) -> Self {
        match index {
            0 => Self::Person,
            1 => Self::Bicycle,
            2 => Self::Car,
            3 => Self::Motorcycle,
            4 => Self::Airplane,
            5 => Self::Bus,
            6 => Self::Train,
            7 => Self::Truck,
            8 => Self::Boat,
            9 => Self::Trafficlight,
            10 => Self::Firehydrant,
            11 => Self::Stopsign,
            12 => Self::Parkingmeter,
            13 => Self::Bench,
            14 => Self::Bird,
            15 => Self::Cat,
            16 => Self::Dog,
            17 => Self::Horse,
            18 => Self::Sheep,
            19 => Self::Cow,
            20 => Self::Elephant,
            21 => Self::Bear,
            22 => Self::Zebra,
            23 => Self::Giraffe,
            24 => Self::Backpack,
            25 => Self::Umbrella,
            26 => Self::Handbag,
            27 => Self::Tie,
            28 => Self::Suitcase,
            29 => Self::Frisbee,
            30 => Self::Skis,
            31 => Self::Snowboard,
            32 => Self::Sportsball,
            33 => Self::Kite,
            34 => Self::Baseballbat,
            35 => Self::Baseballglove,
            36 => Self::Skateboard,
            37 => Self::Surfboard,
            38 => Self::Tennisracket,
            39 => Self::Bottle,
            40 => Self::Wineglass,
            41 => Self::Cup,
            42 => Self::Fork,
            43 => Self::Knife,
            44 => Self::Spoon,
            45 => Self::Bowl,
            46 => Self::Banana,
            47 => Self::Apple,
            48 => Self::Sandwich,
            49 => Self::Orange,
            50 => Self::Broccoli,
            51 => Self::Carrot,
            52 => Self::Hotdog,
            53 => Self::Pizza,
            54 => Self::Donut,
            55 => Self::Cake,
            56 => Self::Chair,
            57 => Self::Couch,
            58 => Self::Pottedplant,
            59 => Self::Bed,
            60 => Self::Diningtable,
            61 => Self::Toilet,
            62 => Self::Tv,
            63 => Self::Laptop,
            64 => Self::Mouse,
            65 => Self::Remote,
            66 => Self::Keyboard,
            67 => Self::Cellphone,
            68 => Self::Microwave,
            69 => Self::Oven,
            70 => Self::Toaster,
            71 => Self::Sink,
            72 => Self::Refrigerator,
            73 => Self::Book,
            74 => Self::Clock,
            75 => Self::Vase,
            76 => Self::Scissors,
            77 => Self::Teddybear,
            78 => Self::Hairdrier,
            79 => Self::Toothbrush,
            _ => unimplemented!(),
        }
    }
}

impl From<YOLOObjectLabel> for String {
    fn from(label: YOLOObjectLabel) -> Self {
        match label {
            YOLOObjectLabel::Person => "Person",
            YOLOObjectLabel::Bicycle => "Bicycle",
            YOLOObjectLabel::Car => "Car",
            YOLOObjectLabel::Motorcycle => "Motorcycle",
            YOLOObjectLabel::Airplane => "Airplane",
            YOLOObjectLabel::Bus => "Bus",
            YOLOObjectLabel::Train => "Train",
            YOLOObjectLabel::Truck => "Truck",
            YOLOObjectLabel::Boat => "Boat",
            YOLOObjectLabel::Trafficlight => "Trafficlight",
            YOLOObjectLabel::Firehydrant => "Firehydrant",
            YOLOObjectLabel::Stopsign => "Stopsign",
            YOLOObjectLabel::Parkingmeter => "Parkingmeter",
            YOLOObjectLabel::Bench => "Bench",
            YOLOObjectLabel::Bird => "Bird",
            YOLOObjectLabel::Cat => "Cat",
            YOLOObjectLabel::Dog => "Dog",
            YOLOObjectLabel::Horse => "Horse",
            YOLOObjectLabel::Sheep => "Sheep",
            YOLOObjectLabel::Cow => "Cow",
            YOLOObjectLabel::Elephant => "Elephant",
            YOLOObjectLabel::Bear => "Bear",
            YOLOObjectLabel::Zebra => "Zebra",
            YOLOObjectLabel::Giraffe => "Giraffe",
            YOLOObjectLabel::Backpack => "Backpack",
            YOLOObjectLabel::Umbrella => "Umbrella",
            YOLOObjectLabel::Handbag => "Handbag",
            YOLOObjectLabel::Tie => "Tie",
            YOLOObjectLabel::Suitcase => "Suitcase",
            YOLOObjectLabel::Frisbee => "Frisbee",
            YOLOObjectLabel::Skis => "Skis",
            YOLOObjectLabel::Snowboard => "Snowboard",
            YOLOObjectLabel::Sportsball => "Sportsball",
            YOLOObjectLabel::Kite => "Kite",
            YOLOObjectLabel::Baseballbat => "Baseballbat",
            YOLOObjectLabel::Baseballglove => "Baseballglove",
            YOLOObjectLabel::Skateboard => "Skateboard",
            YOLOObjectLabel::Surfboard => "Surfboard",
            YOLOObjectLabel::Tennisracket => "Tennisracket",
            YOLOObjectLabel::Bottle => "Bottle",
            YOLOObjectLabel::Wineglass => "Wineglass",
            YOLOObjectLabel::Cup => "Cup",
            YOLOObjectLabel::Fork => "Fork",
            YOLOObjectLabel::Knife => "Knife",
            YOLOObjectLabel::Spoon => "Spoon",
            YOLOObjectLabel::Bowl => "Bowl",
            YOLOObjectLabel::Banana => "Banana",
            YOLOObjectLabel::Apple => "Apple",
            YOLOObjectLabel::Sandwich => "Sandwich",
            YOLOObjectLabel::Orange => "Orange",
            YOLOObjectLabel::Broccoli => "Broccoli",
            YOLOObjectLabel::Carrot => "Carrot",
            YOLOObjectLabel::Hotdog => "Hotdog",
            YOLOObjectLabel::Pizza => "Pizza",
            YOLOObjectLabel::Donut => "Donut",
            YOLOObjectLabel::Cake => "Cake",
            YOLOObjectLabel::Chair => "Chair",
            YOLOObjectLabel::Couch => "Couch",
            YOLOObjectLabel::Pottedplant => "Pottedplant",
            YOLOObjectLabel::Bed => "Bed",
            YOLOObjectLabel::Diningtable => "Diningtable",
            YOLOObjectLabel::Toilet => "Toilet",
            YOLOObjectLabel::Tv => "Tv",
            YOLOObjectLabel::Laptop => "Laptop",
            YOLOObjectLabel::Mouse => "Mouse",
            YOLOObjectLabel::Remote => "Remote",
            YOLOObjectLabel::Keyboard => "Keyboard",
            YOLOObjectLabel::Cellphone => "Cellphone",
            YOLOObjectLabel::Microwave => "Microwave",
            YOLOObjectLabel::Oven => "Oven",
            YOLOObjectLabel::Toaster => "Toaster",
            YOLOObjectLabel::Sink => "Sink",
            YOLOObjectLabel::Refrigerator => "Refrigerator",
            YOLOObjectLabel::Book => "Book",
            YOLOObjectLabel::Clock => "Clock",
            YOLOObjectLabel::Vase => "Vase",
            YOLOObjectLabel::Scissors => "Scissors",
            YOLOObjectLabel::Teddybear => "Teddybear",
            YOLOObjectLabel::Hairdrier => "Hairdrier",
            YOLOObjectLabel::Toothbrush => "Toothbrush",
        }
        .to_string()
    }
}
#[derive(
    Debug,
    Clone,
    Copy,
    Serialize,
    Deserialize,
    PathIntrospect,
    PathSerialize,
    PathDeserialize,
    PartialEq,
)]
pub enum RobocupObjectLabel {
    Ball = 0,
    GoalPost = 1,
    LSpot = 2,
    PenaltySpot = 3,
    Robot = 4,
    TSpot = 5,
    XSpot = 6,
    Person = 7,
}

impl RobocupObjectLabel {
    pub fn from_index(index: usize) -> Self {
        match index {
            0 => Self::Ball,
            1 => Self::GoalPost,
            2 => Self::LSpot,
            3 => Self::PenaltySpot,
            4 => Self::Robot,
            5 => Self::TSpot,
            6 => Self::XSpot,
            7 => Self::Person,
            _ => unimplemented!(),
        }
    }
}

impl From<RobocupObjectLabel> for String {
    fn from(label: RobocupObjectLabel) -> Self {
        match label {
            RobocupObjectLabel::Ball => "Ball",
            RobocupObjectLabel::GoalPost => "GoalPost",
            RobocupObjectLabel::LSpot => "LSpot",
            RobocupObjectLabel::PenaltySpot => "PenaltySpot",
            RobocupObjectLabel::Robot => "Robot",
            RobocupObjectLabel::TSpot => "TSpot",
            RobocupObjectLabel::XSpot => "XSpot",
            RobocupObjectLabel::Person => "Person",
        }
        .to_string()
    }
}
