[package]
edition = "2021"
license = "GPL-3.0-only"
name = "communication_server"
version = "0.1.0"

[dependencies]
communication = {path = "../../crates/communication"}
ctrlc = {version = "3.2.1", features = ["termination"]}
tokio-util = "0.7.3"
