pub enum Action {
    Unstiff,
    SitDown,
    Penalize,
    FallSafely,
    StandUp,
    Stand,
    Dribble,
    DefendGoal,
    DefendKickOff,
    DefendLeft,
    DefendRight,
    SupportStriker,
    Search,
    SearchForLostBall,
    WalkToKickOff,
}
