[package]
name = "twix_visualization"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
coordinate_systems = { workspace = true }
eframe = { workspace = true }
geometry = { workspace = true }
linear_algebra = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
types = { workspace = true }
