#!/bin/bash

# Get base directory for better referencing
BASEDIR=`cd $(dirname $0); pwd -P`
BASEDIR=${BASEDIR%/*}

source "${BASEDIR}/scripts/lib/msg.sh"
source "${BASEDIR}/scripts/lib/time.sh"
source "${BASEDIR}/scripts/lib/compile.sh"
source "${BASEDIR}/scripts/lib/upload.sh"
source "${BASEDIR}/scripts/lib/naonet.sh"
source "${BASEDIR}/scripts/lib/numberToIP.sh"
source "${BASEDIR}/scripts/lib/docker.sh"

function helpMenu {
  echo "Kills the tuhhNao process on the given naos"
  echo ""
  echo "Usage: $0 [OPTIONS] NAO[s]"
  echo ""
  echo " -h, --help   show this help"
  echo " Nao          either hostname(s), IP(s) or number(s) of the NAO(s)"
}



function run {

  # a list of NAOs that are prepared
  NAOS=()

  while [[ "$1" =~ ^- ]]; do
    case "$1" in
      "-h" | "--help")
        helpMenu
        return 0
        ;;
      *)
        msg -e "Failed to parse \"$1\"!"
        helpMenu
        return 1
        ;;
    esac
    shift
  done

  while [ "$#" -gt 0 ]; do
    NAOS+=($(numberToIP "$1"))
    shift
  done

  for index in ${!NAOS[*]}; do
    msg -n "Killing ${NAOS[index]}."
    naocmd "${BASEDIR}" "${NAOS[index]}" "killall -9 tuhhNao"
    if [ "$?" -ne 0 ]; then
      msg -e "Failed to kill ${NAOS[index]}!"
      return 1
    fi
  done

  return 0
}

handleDocker "${BASEDIR}" "$@"
