#!/usr/bin/env bash

# Get base directory for better referencing
BASE_DIRECTORY=`cd $(dirname $0); pwd -P`
BASE_DIRECTORY=${BASE_DIRECTORY%/*}

# The tuhh_autoload.json
tuhh_autoload=${BASE_DIRECTORY}/etc/configuration/location/default/tuhh_autoload.json


# Functions
function help_menu {
  echo "Usage: $0 [Options]"
  echo "returns string of active moduleSetup."
  echo ""
  echo "Options"
  echo "--help  help screen"
  echo "-s, --set <NameOfModuleSetup | f, d, r>"
  echo "            f - fullvisionfake,"
  echo "            d - default,"
  echo "            r - replay"
  echo "            o - oldWalking"
  echo "            p - positionFake"
  echo ""
  echo "example:"
  echo " \"'$0 -s f\", -> sets moduleSetup to fullVisionFake"
  echo " \"'$0 -s replay\", -> sets moduleSetup to replay"

}


##Parse inputs
# Set defaults
HELP="NO"
# Parse arguments
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
  -s|--set)
  TARGET="$2"
  shift # past argument
  shift # past value
  ;;
  -h|--help)
  HELP="YES"
  shift # past argument
  ;;
  *) # catch unknown input
  HELP="YES"
  echo "Unkown argument - read help menu:"
  shift
esac
done

## MAIN
#check if help tag is set.
if [ $HELP == "YES" ]; then
  help_menu
  exit
fi

if ! [ -z $TARGET ]; then
  case $TARGET in
    "default"|"d")
      sed -i "s/moduleSetup\(.*\)\"\(.*\)\",/moduleSetup\1\"default\",/g" $tuhh_autoload
      ;;
    "fullVisionFake" | "fullvisionfake" | "f")
      sed -i "s/moduleSetup\(.*\)\"\(.*\)\",/moduleSetup\1\"fullVisionFake\",/g" $tuhh_autoload
      ;;
    "replay" | "r")
      sed -i "s/moduleSetup\(.*\)\"\(.*\)\",/moduleSetup\1\"replay\",/g" $tuhh_autoload
      ;;
    "oldWalking" | "o")
      sed -i "s/moduleSetup\(.*\)\"\(.*\)\",/moduleSetup\1\"oldWalking\",/g" $tuhh_autoload
      ;;
    "positionFake" | "p")
      sed -i "s/moduleSetup\(.*\)\"\(.*\)\",/moduleSetup\1\"positionFake\",/g" $tuhh_autoload
      ;;
    *)
    echo "Failed to parse argument $TARGET"
    ;;
esac
fi

#return stuff
IN=$(sed -e '/*/p' $tuhh_autoload)
arrIN=(${IN//\"/ })
echo ${arrIN[3]}

