#!/bin/bash

##VAR
allowedSetups='{default, fullVisionFake, replay, oldWalking}'

# Get base directory for better referencing
BASEDIR=`cd $(dirname $0); pwd -P`
BASEDIR=${BASEDIR%/*}

# The tuhh_autoload.json
tuhh_autoload=${BASEDIR}/home/configuration/location/default/tuhh_autoload.json


# Functions
function helpMsg {
  echo "Usage: $0 [Options]"
  echo "returns string of active moduleSetup."
  echo ""
  echo "Options"
  echo "--help  help screen"
  echo "-s, --set <NameOfModuleSetup | f, d, r, ow>"
  echo "            f - fullvisionfake,"
  echo "            d - default,"
  echo "            r - replay,"
  echo "            ow - oldWalking"
  echo ""
  echo "example:"
  echo " \"'$0 -s f\", -> sets moduleSetup to fullVisionFake"
  echo " \"'$0 -s replay\", -> sets moduleSetup to replay"

}


##Parse inputs
# Set defaults
HELP="NO"
# Parse arguments
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
  -s|--set)
  TARGET="$2"
  shift # past argument
  shift # past value
  ;;
  -h|--help)
  HELP="YES"
  shift # past argument
  ;;
  *) # catch unknown input
  HELP="YES"
  echo "Unkown argument! - read help menu:"
  shift
esac
done

## MAIN
#check if help tag is set.
if [ $HELP == "YES" ]; then
  helpMsg
  exit
fi

if ! [ -z $TARGET ]; then
  case $TARGET in
    "default"|"d")
    sed -i "/moduleSetup/c\  \"moduleSetup\" : \"default\", //$allowedSetups" $tuhh_autoload
    ;;
    "fullVisionFake" | "fullvisionfake" | "f")
    sed -i "/moduleSetup/c\  \"moduleSetup\" : \"fullVisionFake\", //$allowedSetups" $tuhh_autoload
    ;;
    "replay" | "r")
    sed -i "/moduleSetup/c\  \"moduleSetup\" : \"replay\", //$allowedSetups" $tuhh_autoload
    ;;
    "oldWalking" | "ow")
    sed -i "/moduleSetup/c\  \"moduleSetup\" : \"oldWalking\", //$allowedSetups" $tuhh_autoload
    ;;
    *)
    echo "Failed to parse argument $TARGET"
    echo "Valid arguments: $allowedSetups"
    ;;
esac
fi

#return stuff
IN=$(sed -e '/*/p' $tuhh_autoload)
arrIN=(${IN//\"/ })
echo ${arrIN[3]}

