#!/bin/bash

# Get base directory for better referencing
BASEDIR=`cd $(dirname $0); pwd -P`
BASEDIR=${BASEDIR%/*}

source "${BASEDIR}/scripts/lib/msg.sh"
source "${BASEDIR}/scripts/lib/time.sh"
source "${BASEDIR}/scripts/lib/compile.sh"
source "${BASEDIR}/scripts/lib/upload.sh"
source "${BASEDIR}/scripts/lib/naonet.sh"
source "${BASEDIR}/scripts/lib/numberToIP.sh"
source "${BASEDIR}/scripts/lib/docker.sh"

function helpMenu {
  echo "Usage: $0 [OPTIONS] NAO..."
  echo ""
  echo "Options"
  echo " -b, --build-type BUILD_TYPE       use the specified build type (one out of Debug, Develop, Release)"
  echo " -t, --target                      choose the target (nao5, nao6)"
  echo " -n, --network NETWORK             the network to which the robots should be set (e.g. ETH or SPL_A)"
  echo " -j, --jobs                        the amount of processes used for compilation"
  echo " -h, --help                        show this help"
  echo " --enable-aliveness                enables aliveness before uploading to the nao"
  echo " --enable-debug                    enables debug before uploading to the nao"
  echo " --enable-config                   enables config before uploading to the nao"
  echo ""
  echo "Nao"
  echo " either hostname, IP or number of the NAO"
}

function printErrorMessage {
  case $1 in
    0)
	  msg -s "Finished deploying to $2"
      ;;
    1)
      msg -e "Failed to upload to nao $2"
      ;;
    2)
      msg -e "Failed to restart the hulks service for nao $2"
      ;;
  esac
}

function run {
  # pregame deployment always happens with target NAO
  TARGET="nao6"
  # default pregame build type is Release but it can be overridden
  BUILD_TYPE="Release"
  # a list of NAOs that are prepared
  NAOS=()
  ERRORS=()
  # default network is ethernet
  NETWORK=ETH
  # set default job number to cores + 1
  JOBS=$(njobs)
  # prepare parameters
  PARAMETERS=""
  # whether aliveness, debug, configuration should be enabled
  ENABLE_ALIVENESS=false
  ENABLE_DEBUG=false
  ENABLE_CONFIG=false

  while [ "$#" -gt 0 ]; do
    if [[ $1 =~ ^- ]] && [[ ! $1 =~ ^-- ]]; then
      PARAMETERS+=$(echo "${1:1}" | sed -e "s/\(.\)/ -\1/g")
    else
      PARAMETERS+=" $1"
    fi
    shift
  done
  eval set -- "${PARAMETERS}";

  while [[ "$1" =~ ^- ]]; do
    case "$1" in
      "-b" | "--build-type")
        shift
        if [ "$#" -eq 0 ]; then
          msg -e "--build-type needs a build type as parameter!"
          helpMenu
          return 1
        fi
        BUILD_TYPE="$1"
        ;;
      "-t" | "--target")
        shift
        TARGET="$1"
        ;;
      "-n" | "--network")
        shift
        if [ "$#" -eq 0 ]; then
          msg -e "--network needs a network as parameter!"
          helpMenu
          return 1
        fi
        NETWORK="$1"
        ;;
      "-j" | "--jobs")
        shift
        if [ "$#" -eq 0 ]; then
          msg -e "--jobs needs a job number!"
          helpMenu
          return 1
        fi
        JOBS=$1
        ;;
      "-h" | "--help")
        helpMenu
        return 0
        ;;
      "--enable-aliveness")
        ENABLE_ALIVENESS=true
        ;;
      "--enable-debug")
        ENABLE_DEBUG=true
        ;;
      "--enable-config")
        ENABLE_CONFIG=true
        ;;
      *)
        msg -e "Failed to parse \"$1\"!"
        helpMenu
        return 1
        ;;
    esac
    shift
  done

  if [ "$#" -lt 1 ]; then
    helpMenu
    return 1
  fi

  while [ "$#" -gt 0 ]; do
    NAOS+=($(numberToIP "$1"))
    shift
  done

  if [ "${BUILD_TYPE}" == "" ]; then
    msg -e "It seems you haven't compiled before! You need to specify a build type to this script."
    return 1
  fi

  # compile once before uploading
  msg -n "Compiling with build type ${BUILD_TYPE}."
  set_start_time
  compile "${BASEDIR}" "${TARGET}" "${BUILD_TYPE}" false ${JOBS}
  if [ "$?" -ne 0 ]; then
    msg -e "Compilation failed!"
    return 1
  fi
  get_time_diff
  msg -s "Compilation finished successfully in ${DIFF}!"

  msg -n "aliveness: $(if ${ENABLE_ALIVENESS} ; then echo enabled; else echo disabled; fi), debug: $(if ${ENABLE_DEBUG} ; then echo enabled; else echo disabled; fi), config: $(if ${ENABLE_CONFIG} ; then echo enabled; else echo disabled; fi)"
  if ${ENABLE_ALIVENESS} ; then
    sed -i 's/"network.enableAliveness": false/"network.enableAliveness": true/g' "${BASEDIR}/home/configuration/location/default/sdk.json"
  else
    sed -i 's/"network.enableAliveness": true/"network.enableAliveness": false/g' "${BASEDIR}/home/configuration/location/default/sdk.json"
  fi

  if ${ENABLE_DEBUG} ; then
    sed -i 's/"network.enableDebugTCPTransport": false/"network.enableDebugTCPTransport": true/g' "${BASEDIR}/home/configuration/location/default/sdk.json"
  else
    sed -i 's/"network.enableDebugTCPTransport": true/"network.enableDebugTCPTransport": false/g' "${BASEDIR}/home/configuration/location/default/sdk.json"
  fi

  if ${ENABLE_CONFIG} ; then
    sed -i 's/"network.enableConfiguration": false/"network.enableConfiguration": true/g' "${BASEDIR}/home/configuration/location/default/sdk.json"
  else
    sed -i 's/"network.enableConfiguration": true/"network.enableConfiguration": false/g' "${BASEDIR}/home/configuration/location/default/sdk.json"
  fi

  ERROR=0
  for index in ${!NAOS[*]}; do
    msg -n "Deploying to ${NAOS[index]}."
    msg -n "Stopping ${NAOS[index]}."
    if [ "${TARGET}" == "nao6" ]; then
      naocmd "${BASEDIR}" "${NAOS[index]}" "systemctl --user stop hulk.service"
    else
      naocmd "${BASEDIR}" "${NAOS[index]}" "sudo /etc/init.d/hulk stop; killall -SIGTERM tuhhNao 2>/dev/null; exit 0"
    fi
    if [ "$?" -ne 0 ]; then
      msg -e "Failed to stop ${NAOS[index]}!"
      return 1
    fi
    # true true is for replacing configuration with own configuration
    upload "${BASEDIR}" "${NAOS[index]}" "${BUILD_TYPE}" true true "${TARGET}"
    if [ "$?" -ne 0 ]; then
      ERRORS[index]=1
      printErrorMessage 1 ${NAOS[index]}
      ERROR=1
      continue
    fi
    if [ "${TARGET}" == "nao6" ]; then
      naocmd "${BASEDIR}" "${NAOS[index]}" "/home/nao/.local/bin/setNetwork ${NETWORK}; systemctl --user restart lola-hulks; systemctl --user start hulk"
    else
      naocmd "${BASEDIR}" "${NAOS[index]}" "sudo /etc/init.d/naoqi restart; /home/nao/bin/setNetwork ${NETWORK}; sudo /etc/init.d/hulk start"
    fi
    if [ "$?" -ne 0 ]; then
      msg -e "Failed to restart the hulk service on ${NAOS[index]}!"
      ERRORS[index]=2
      printErrorMessage 2 ${NAOS[index]}
      ERROR=1
      continue
    fi
    ERRORS[index]=0
    msg -s "Finished deploying to ${NAOS[index]}!"
  done

  echo "--------------------"
  echo "Summary for pregame:"

  for index in ${!ERRORS[*]}
  do
    printErrorMessage ${ERRORS[index]} ${NAOS[index]}
  done

  return $ERROR
}

handleDocker "${BASEDIR}" "$@"
