from _typeshed import Incomplete
from absl.testing import absltest

class MuJoCoRenderTest(absltest.TestCase):
    gl: Incomplete
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    model: Incomplete
    data: Incomplete
    def test_can_render(self) -> None: ...
    def test_safe_to_free_context_twice(self) -> None: ...
    def test_mjrrect_repr(self) -> None: ...
