[project]
name = "robot-dimensions"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = ["numpy>=1.2.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
