[package]
name = "opn"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
color-eyre = { workspace = true }
byteorder = { workspace = true }
sha2 = { workspace = true }
