[package]
name = "localization-3d"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
booster.workspace = true
color-eyre = { workspace = true }
coordinate_systems = { workspace = true }
fagra = { workspace = true }
itertools.workspace = true
kinematics = { workspace = true }
linear_algebra = { workspace = true }
localization-fagra = { workspace = true }
nalgebra = { workspace = true }
projection = { workspace = true }
ros-z = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }

[dev-dependencies]
field_mark_association.workspace = true
json5.workspace = true
mcap.workspace = true
serde_json.workspace = true
