#!/usr/bin/env bash
set -euo pipefail

CURRENT_DATE="$(date +%Y-%m-%dT%H:%M:%S.%3N%:z)"
INTERNAL_LOG_PATH="/home/booster/hulk/logs/${CURRENT_DATE}"

mkdir -p "${INTERNAL_LOG_PATH}"
ln -sfn "${INTERNAL_LOG_PATH}" "/home/booster/hulk/logs/latest"
touch "${INTERNAL_LOG_PATH}/hulk.out" "${INTERNAL_LOG_PATH}/hulk.err"
chown -R booster:booster /home/booster/hulk/logs

/usr/local/bin/podman exec \
  --env RUST_BACKTRACE=1 \
  --user $(id -u booster) \
  hulk \
  /home/booster/hulk/bin/hulk_ros_z \
  --robot {} \
  --location default-location \
  --parameter-root etc/parameters/ros_z \
  --router tcp/127.0.0.1:7447 \
  --log-path "${INTERNAL_LOG_PATH}" \
  > >(tee "${INTERNAL_LOG_PATH}/hulk.out") \
  2> >(tee "${INTERNAL_LOG_PATH}/hulk.err")
