#!/usr/bin/env bash

CURRENT_DATE=$(date +%Y-%m-%dT%H:%M:%S.%3N%:z)
INTERNAL_LOG_PATH=/home/booster/hulk/logs/${CURRENT_DATE}

mkdir -p ${INTERNAL_LOG_PATH}

ln -sf ${INTERNAL_LOG_PATH}/hulk.out ${INTERNAL_LOG_PATH}/../hulk.out
ln -sf ${INTERNAL_LOG_PATH}/hulk.err ${INTERNAL_LOG_PATH}/../hulk.err

HOST_TEGRA_LIB_PATH="/usr/lib/aarch64-linux-gnu/tegra"
DEVICES="--device nvidia.com/gpu=all"
HARDWARE_ID="$(jetson_release -s | grep 'Serial Number:' | grep '[0-9]*$' -o)"

sudo podman rm hulk
sudo podman run -it --rm \
  --privileged \
  --network=host \
  $DEVICES \
  -v ${HOST_TEGRA_LIB_PATH}:${HOST_TEGRA_LIB_PATH} \
  -v /home/booster/hulk:/home/booster/hulk \
  -v /home/booster/.cache:/home/booster/.cache \
  -v /home/booster/.cargo:/root/.cargo \
  --env LD_LIBRARY_PATH=${HOST_TEGRA_LIB_PATH}:$LD_LIBRARY_PATH \
  --env ORT_DYLIB_PATH=/usr/local/lib/libonnxruntime.so \
  --env HARDWARE_ID=${HARDWARE_ID} \
  --name hulk \
  hulk-runtime:latest \
  bash -c "cd /home/booster/hulk &&
    ./bin/hulk --log-path ${INTERNAL_LOG_PATH}
     > >(tee ${INTERNAL_LOG_PATH}/hulk.out)
    2> >(tee ${INTERNAL_LOG_PATH}/hulk.err)
  "
