#!/usr/bin/env bash
set -euo pipefail

CURRENT_DATE="$(date +%Y-%m-%dT%H:%M:%S.%3N%:z)"
INTERNAL_LOG_PATH="/home/booster/hulk/logs/${CURRENT_DATE}"

mkdir -p "${INTERNAL_LOG_PATH}"
ln -sfn "${INTERNAL_LOG_PATH}" "/home/booster/hulk/logs/latest"

/usr/local/bin/podman exec \
  --env RUST_BACKTRACE=1 \
  hulk \
  /home/booster/hulk/bin/hulk \
    --log-path "${INTERNAL_LOG_PATH}" \
  > >(tee "${INTERNAL_LOG_PATH}/hulk.out") \
  2> >(tee "${INTERNAL_LOG_PATH}/hulk.err")
