[package]
edition = "2021"
license = "GPL-3.0-only"
name = "context_attribute"
version = "0.1.0"

[dependencies]
proc-macro-error = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lib]
proc-macro = true
