[project]
name = "learned-identification"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
  "click>=8.1.8",
  "cmaes>=0.11.1",
  "mcap>=1.2.1",
  "mediapy>=1.2.2",
  "msgpack>=1.1.0",
  "mujoco>=3.2.5",
  "numpy>=2.1.3",
  "optuna-dashboard>=0.17.0",
  "optuna>=4.1.0",
  "pymysql>=1.1.1",
  "pyqt6>=6.7.1",
  "tqdm>=4.67.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
