use std::{path::Path, time::Duration};

use source_analyzer::{
    cyclers::{CyclerKind, Cyclers},
    error::Error,
    manifest::{CyclerManifest, FrameworkManifest},
};

pub fn collect_hulk_cyclers(root: impl AsRef<Path>) -> Result<Cyclers, Error> {
    let manifest = FrameworkManifest {
        cyclers: vec![
            CyclerManifest {
                name: "Vision",
                kind: CyclerKind::Perception,
                instances: vec![""],
                setup_nodes: vec!["vision::image_receiver"],
                nodes: vec![
                    "vision::field_border_detection",
                    "vision::image_segmenter",
                    "vision::line_detection",
                    "vision::segment_filter",
                ],
                execution_time_warning_threshold: Some(Duration::from_secs_f32(1.0 / 30.0)),
            },
            CyclerManifest {
                name: "ObjectDetection",
                kind: CyclerKind::Perception,
                instances: vec![""],
                setup_nodes: vec!["object_detection::image_receiver"],
                nodes: vec![
                    "object_detection::object_detection",
                    // "object_detection::pose_detection",
                    // "object_detection::pose_filter",
                    // "object_detection::pose_interpretation",
                ],
                execution_time_warning_threshold: Some(Duration::from_secs_f32(1.0 / 30.0)),
            },
            CyclerManifest {
                name: "Motion",
                kind: CyclerKind::Perception,
                instances: vec![""],
                setup_nodes: vec!["motion::sensor_data_receiver"],
                nodes: vec![
                    "motion::look_at",
                    "motion::look_around",
                    "motion::head_motion",
                    "motion::booster::rotate_head",
                    "motion::booster::kick",
                    "motion::booster::walking",
                    "motion::booster::stand_up",
                    "motion::hulk::command_sender",
                    // "motion::hulk::walking",
                    "motion::hulk::motor_commands_collector",
                ],
                execution_time_warning_threshold: Some(Duration::from_secs_f32(1.0 / 100.0)),
            },
            CyclerManifest {
                name: "HslNetwork",
                kind: CyclerKind::Perception,
                instances: vec![""],
                setup_nodes: vec!["hsl_network::message_receiver"],
                nodes: vec!["hsl_network::message_filter"],
                execution_time_warning_threshold: None,
            },
            CyclerManifest {
                name: "WorldState",
                kind: CyclerKind::RealTime,
                instances: vec![""],
                setup_nodes: vec!["world_state::trigger"],
                nodes: vec![
                    "world_state::active_vision",
                    "world_state::ball_filter",
                    "world_state::ball_state_composer",
                    "world_state::behavior::node",
                    "world_state::button_event_handler",
                    "world_state::camera_matrix_calculator",
                    "world_state::fake_odometry",
                    "world_state::game_controller_filter",
                    "world_state::game_controller_state_filter",
                    "world_state::ground_provider",
                    "world_state::kinematics_provider",
                    "world_state::led_handler",
                    "world_state::localization",
                    "world_state::obstacle_filter",
                    "world_state::obstacle_receiver",
                    "world_state::primary_state_filter",
                    "world_state::robot_mode_handler",
                    "world_state::role_assignment",
                    "world_state::rule_obstacle_composer",
                    "world_state::safe_pose_checker",
                    "world_state::search_suggestor",
                    "world_state::team_ball_receiver",
                    "world_state::time_to_reach_kick_position",
                    "world_state::world_state_composer",
                    "world_state::world_to_field_provider",
                ],
                execution_time_warning_threshold: Some(Duration::from_secs_f32(1.0 / 100.0)),
            },
            // CyclerManifest {
            //     name: "Audio",
            //     kind: CyclerKind::Perception,
            //     instances: vec![""],
            //     setup_nodes: vec!["audio::microphone_recorder"],
            //     nodes: vec!["audio::whistle_detection"],
            //     execution_time_warning_threshold: None,
            // },
            // CyclerManifest {
            //     name: "Image",
            //     kind: CyclerKind::Perception,
            //     instances: vec!["Rectified", "StereonetDepth"],
            //     setup_nodes: vec!["sensor_receiver::image_receiver"],
            //     nodes: vec![],
            //     execution_time_warning_threshold: None,
            // },
            CyclerManifest {
                name: "FallDownState",
                kind: CyclerKind::Perception,
                instances: vec![""],
                setup_nodes: vec!["sensor_receiver::fall_down_state_receiver"],
                nodes: vec![],
                execution_time_warning_threshold: None,
            },
            CyclerManifest {
                name: "ButtonEvent",
                kind: CyclerKind::Perception,
                instances: vec![""],
                setup_nodes: vec!["sensor_receiver::button_event_receiver"],
                nodes: vec![],
                execution_time_warning_threshold: None,
            },
            CyclerManifest {
                name: "Odometry",
                kind: CyclerKind::Perception,
                instances: vec![""],
                setup_nodes: vec!["sensor_receiver::odometer_receiver"],
                nodes: vec![],
                execution_time_warning_threshold: None,
            },
        ],
    };

    Cyclers::try_from_manifest(manifest, root)
}
