[package]
edition = "2021"
license = "GPL-3.0-only"
name = "framework"
version = "0.1.0"

[dependencies]
parking_lot = { workspace = true }
structs = { workspace = true }
types = { workspace = true }

[build-dependencies]
build_script_helpers = { workspace = true }
color-eyre = { workspace = true }
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
source_analyzer = { workspace = true }
