[package]
name = "framework"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
parking_lot = { workspace = true }
serde = { workspace = true }
