[package]
edition = "2021"
license = "GPL-3.0-only"
name = "build_script_helpers"
version = "0.1.0"

[dependencies]
anyhow = "1.0.59"
proc-macro2 = { workspace = true }
source_analyzer = { workspace = true }
