# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mate/ui/views/map/layer/ballSearch_config_view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BallSearchConfig(object):
    def setupUi(self, BallSearchConfig):
        BallSearchConfig.setObjectName("BallSearchConfig")
        BallSearchConfig.resize(591, 613)
        self.verticalLayout = QtWidgets.QVBoxLayout(BallSearchConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(BallSearchConfig)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 579, 559))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(4, 4, 4, 4)
        self.formLayout.setObjectName("formLayout")
        self.nameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.centerLabel = QtWidgets.QLabel(self.groupBox)
        self.centerLabel.setObjectName("centerLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.centerLabel)
        self.centerWidget = QtWidgets.QWidget(self.groupBox)
        self.centerWidget.setObjectName("centerWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centerWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_center_x = QtWidgets.QLabel(self.centerWidget)
        self.label_center_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_x.setObjectName("label_center_x")
        self.horizontalLayout_2.addWidget(self.label_center_x)
        self.spin_center_x = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_x.setMinimum(-99.99)
        self.spin_center_x.setObjectName("spin_center_x")
        self.horizontalLayout_2.addWidget(self.spin_center_x)
        self.label_center_y = QtWidgets.QLabel(self.centerWidget)
        self.label_center_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_y.setObjectName("label_center_y")
        self.horizontalLayout_2.addWidget(self.label_center_y)
        self.spin_center_y = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_y.setMinimum(-99.99)
        self.spin_center_y.setObjectName("spin_center_y")
        self.horizontalLayout_2.addWidget(self.spin_center_y)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.centerWidget)
        self.enabledLabel = QtWidgets.QLabel(self.groupBox)
        self.enabledLabel.setObjectName("enabledLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.enabledLabel)
        self.enabledCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.enabledCheckBox.setChecked(True)
        self.enabledCheckBox.setObjectName("enabledCheckBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.enabledCheckBox)
        self.nameLabel = QtWidgets.QLabel(self.groupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(4, 4, 4, 4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.KeyLabel = QtWidgets.QLabel(self.groupBox_2)
        self.KeyLabel.setObjectName("KeyLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.KeyLabel)
        self.keyLambdaWidget = QtWidgets.QWidget(self.groupBox_2)
        self.keyLambdaWidget.setObjectName("keyLambdaWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.keyLambdaWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbx_MapKey = QtWidgets.QComboBox(self.keyLambdaWidget)
        self.cbx_MapKey.setEditable(True)
        self.cbx_MapKey.setObjectName("cbx_MapKey")
        self.verticalLayout_4.addWidget(self.cbx_MapKey)
        self.label = QtWidgets.QLabel(self.keyLambdaWidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.edit_MapKeyLambda = QtWidgets.QTextEdit(self.keyLambdaWidget)
        self.edit_MapKeyLambda.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_MapKeyLambda.setTabStopWidth(16)
        self.edit_MapKeyLambda.setObjectName("edit_MapKeyLambda")
        self.verticalLayout_4.addWidget(self.edit_MapKeyLambda)
        self.label_2 = QtWidgets.QLabel(self.keyLambdaWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.keyLambdaWidget)
        self.ProbabilityLabel = QtWidgets.QLabel(self.groupBox_2)
        self.ProbabilityLabel.setObjectName("ProbabilityLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ProbabilityLabel)
        self.probabilityCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.probabilityCheckbox.setChecked(True)
        self.probabilityCheckbox.setObjectName("probabilityCheckbox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.probabilityCheckbox)
        self.ProbabilityNumericLabel = QtWidgets.QLabel(self.groupBox_2)
        self.ProbabilityNumericLabel.setObjectName("ProbabilityNumericLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ProbabilityNumericLabel)
        self.probabilityNumericCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.probabilityNumericCheckbox.setChecked(False)
        self.probabilityNumericCheckbox.setObjectName("probabilityNumericCheckbox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.probabilityNumericCheckbox)
        self.AgeLabel = QtWidgets.QLabel(self.groupBox_2)
        self.AgeLabel.setObjectName("AgeLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.AgeLabel)
        self.ageCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.ageCheckbox.setChecked(True)
        self.ageCheckbox.setObjectName("ageCheckbox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ageCheckbox)
        self.AgeNumericLabel = QtWidgets.QLabel(self.groupBox_2)
        self.AgeNumericLabel.setObjectName("AgeNumericLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.AgeNumericLabel)
        self.ageNumericCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.ageNumericCheckbox.setChecked(False)
        self.ageNumericCheckbox.setObjectName("ageNumericCheckbox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.ageNumericCheckbox)
        self.VoronoiSeedsLabel = QtWidgets.QLabel(self.groupBox_2)
        self.VoronoiSeedsLabel.setObjectName("VoronoiSeedsLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.VoronoiSeedsLabel)
        self.voronoiSeedsCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.voronoiSeedsCheckbox.setChecked(True)
        self.voronoiSeedsCheckbox.setObjectName("voronoiSeedsCheckbox")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.voronoiSeedsCheckbox)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAccept = QtWidgets.QPushButton(BallSearchConfig)
        self.btnAccept.setObjectName("btnAccept")
        self.horizontalLayout.addWidget(self.btnAccept)
        self.btnDiscard = QtWidgets.QPushButton(BallSearchConfig)
        self.btnDiscard.setObjectName("btnDiscard")
        self.horizontalLayout.addWidget(self.btnDiscard)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(BallSearchConfig)
        QtCore.QMetaObject.connectSlotsByName(BallSearchConfig)
        BallSearchConfig.setTabOrder(self.nameLineEdit, self.spin_center_x)
        BallSearchConfig.setTabOrder(self.spin_center_x, self.spin_center_y)
        BallSearchConfig.setTabOrder(self.spin_center_y, self.enabledCheckBox)
        BallSearchConfig.setTabOrder(self.enabledCheckBox, self.edit_MapKeyLambda)
        BallSearchConfig.setTabOrder(self.edit_MapKeyLambda, self.probabilityCheckbox)
        BallSearchConfig.setTabOrder(self.probabilityCheckbox, self.probabilityNumericCheckbox)
        BallSearchConfig.setTabOrder(self.probabilityNumericCheckbox, self.ageCheckbox)
        BallSearchConfig.setTabOrder(self.ageCheckbox, self.ageNumericCheckbox)
        BallSearchConfig.setTabOrder(self.ageNumericCheckbox, self.voronoiSeedsCheckbox)
        BallSearchConfig.setTabOrder(self.voronoiSeedsCheckbox, self.btnAccept)
        BallSearchConfig.setTabOrder(self.btnAccept, self.btnDiscard)
        BallSearchConfig.setTabOrder(self.btnDiscard, self.scrollArea)

    def retranslateUi(self, BallSearchConfig):
        _translate = QtCore.QCoreApplication.translate
        BallSearchConfig.setWindowTitle(_translate("BallSearchConfig", "Form"))
        self.groupBox.setTitle(_translate("BallSearchConfig", "General:"))
        self.centerLabel.setText(_translate("BallSearchConfig", "Center"))
        self.label_center_x.setText(_translate("BallSearchConfig", "X:"))
        self.label_center_y.setText(_translate("BallSearchConfig", "Y:"))
        self.enabledLabel.setText(_translate("BallSearchConfig", "Enabled:"))
        self.nameLabel.setText(_translate("BallSearchConfig", "Name:"))
        self.groupBox_2.setTitle(_translate("BallSearchConfig", "Search:"))
        self.KeyLabel.setText(_translate("BallSearchConfig", "Map key:"))
        self.label.setText(_translate("BallSearchConfig", "def parse(input):"))
        self.label_2.setText(_translate("BallSearchConfig", "return output"))
        self.ProbabilityLabel.setText(_translate("BallSearchConfig", "Probability (in greyscale)"))
        self.ProbabilityNumericLabel.setText(_translate("BallSearchConfig", "Probability value (in %)"))
        self.AgeLabel.setText(_translate("BallSearchConfig", "Age (in redscale)"))
        self.AgeNumericLabel.setText(_translate("BallSearchConfig", "Age value (in seconds)"))
        self.VoronoiSeedsLabel.setText(_translate("BallSearchConfig", "Area seeds (opaque=searching)"))
        self.btnAccept.setText(_translate("BallSearchConfig", "Accept"))
        self.btnDiscard.setText(_translate("BallSearchConfig", "Discard"))

