# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mate/ui/views/map/layer/field_config_view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FieldConfig(object):
    def setupUi(self, FieldConfig):
        FieldConfig.setObjectName("FieldConfig")
        FieldConfig.resize(420, 486)
        self.verticalLayout = QtWidgets.QVBoxLayout(FieldConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(FieldConfig)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -190, 411, 608))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(4, 4, 4, 4)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.groupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.centerLabel = QtWidgets.QLabel(self.groupBox)
        self.centerLabel.setObjectName("centerLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.centerLabel)
        self.centerWidget = QtWidgets.QWidget(self.groupBox)
        self.centerWidget.setObjectName("centerWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centerWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_center_x = QtWidgets.QLabel(self.centerWidget)
        self.label_center_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_x.setObjectName("label_center_x")
        self.horizontalLayout_2.addWidget(self.label_center_x)
        self.spin_center_x = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_x.setMinimum(-99.99)
        self.spin_center_x.setObjectName("spin_center_x")
        self.horizontalLayout_2.addWidget(self.spin_center_x)
        self.label_center_y = QtWidgets.QLabel(self.centerWidget)
        self.label_center_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_y.setObjectName("label_center_y")
        self.horizontalLayout_2.addWidget(self.label_center_y)
        self.spin_center_y = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_y.setMinimum(-99.99)
        self.spin_center_y.setObjectName("spin_center_y")
        self.horizontalLayout_2.addWidget(self.spin_center_y)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.centerWidget)
        self.enabledLabel = QtWidgets.QLabel(self.groupBox)
        self.enabledLabel.setObjectName("enabledLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.enabledLabel)
        self.enabledCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.enabledCheckBox.setChecked(True)
        self.enabledCheckBox.setObjectName("enabledCheckBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.enabledCheckBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(4, 4, 4, 4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.dimensionLabel = QtWidgets.QLabel(self.groupBox_2)
        self.dimensionLabel.setObjectName("dimensionLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dimensionLabel)
        self.dimensionWidget = QtWidgets.QWidget(self.groupBox_2)
        self.dimensionWidget.setObjectName("dimensionWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.dimensionWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_length = QtWidgets.QLabel(self.dimensionWidget)
        self.label_length.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_length.setObjectName("label_length")
        self.horizontalLayout_5.addWidget(self.label_length)
        self.spin_field_length = QtWidgets.QDoubleSpinBox(self.dimensionWidget)
        self.spin_field_length.setObjectName("spin_field_length")
        self.horizontalLayout_5.addWidget(self.spin_field_length)
        self.label_width = QtWidgets.QLabel(self.dimensionWidget)
        self.label_width.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_width.setObjectName("label_width")
        self.horizontalLayout_5.addWidget(self.label_width)
        self.spin_field_width = QtWidgets.QDoubleSpinBox(self.dimensionWidget)
        self.spin_field_width.setObjectName("spin_field_width")
        self.horizontalLayout_5.addWidget(self.spin_field_width)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dimensionWidget)
        self.lineWidthLabel = QtWidgets.QLabel(self.groupBox_2)
        self.lineWidthLabel.setObjectName("lineWidthLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineWidthLabel)
        self.spin_field_lineWidth = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_field_lineWidth.setObjectName("spin_field_lineWidth")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_field_lineWidth)
        self.penaltyMarkerLabel = QtWidgets.QLabel(self.groupBox_2)
        self.penaltyMarkerLabel.setObjectName("penaltyMarkerLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.penaltyMarkerLabel)
        self.penaltyMarkerWidget = QtWidgets.QWidget(self.groupBox_2)
        self.penaltyMarkerWidget.setObjectName("penaltyMarkerWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.penaltyMarkerWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_length_2 = QtWidgets.QLabel(self.penaltyMarkerWidget)
        self.label_length_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_length_2.setObjectName("label_length_2")
        self.horizontalLayout_3.addWidget(self.label_length_2)
        self.spin_field_penaltyMarkerSize = QtWidgets.QDoubleSpinBox(self.penaltyMarkerWidget)
        self.spin_field_penaltyMarkerSize.setObjectName("spin_field_penaltyMarkerSize")
        self.horizontalLayout_3.addWidget(self.spin_field_penaltyMarkerSize)
        self.label_width_2 = QtWidgets.QLabel(self.penaltyMarkerWidget)
        self.label_width_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_width_2.setObjectName("label_width_2")
        self.horizontalLayout_3.addWidget(self.label_width_2)
        self.spin_field_penaltyMarkerDistance = QtWidgets.QDoubleSpinBox(self.penaltyMarkerWidget)
        self.spin_field_penaltyMarkerDistance.setObjectName("spin_field_penaltyMarkerDistance")
        self.horizontalLayout_3.addWidget(self.spin_field_penaltyMarkerDistance)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.penaltyMarkerWidget)
        self.penaltyAreaLabel = QtWidgets.QLabel(self.groupBox_2)
        self.penaltyAreaLabel.setObjectName("penaltyAreaLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.penaltyAreaLabel)
        self.penaltyAreaWidget = QtWidgets.QWidget(self.groupBox_2)
        self.penaltyAreaWidget.setObjectName("penaltyAreaWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.penaltyAreaWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_length_3 = QtWidgets.QLabel(self.penaltyAreaWidget)
        self.label_length_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_length_3.setObjectName("label_length_3")
        self.horizontalLayout_4.addWidget(self.label_length_3)
        self.spin_field_penaltyAreaLength = QtWidgets.QDoubleSpinBox(self.penaltyAreaWidget)
        self.spin_field_penaltyAreaLength.setObjectName("spin_field_penaltyAreaLength")
        self.horizontalLayout_4.addWidget(self.spin_field_penaltyAreaLength)
        self.label_width_3 = QtWidgets.QLabel(self.penaltyAreaWidget)
        self.label_width_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_width_3.setObjectName("label_width_3")
        self.horizontalLayout_4.addWidget(self.label_width_3)
        self.spin_field_penaltyAreaWidth = QtWidgets.QDoubleSpinBox(self.penaltyAreaWidget)
        self.spin_field_penaltyAreaWidth.setObjectName("spin_field_penaltyAreaWidth")
        self.horizontalLayout_4.addWidget(self.spin_field_penaltyAreaWidth)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.penaltyAreaWidget)
        self.centerCircleDiameterLabel = QtWidgets.QLabel(self.groupBox_2)
        self.centerCircleDiameterLabel.setObjectName("centerCircleDiameterLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.centerCircleDiameterLabel)
        self.spin_field_centerCircleDiameter = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_field_centerCircleDiameter.setObjectName("spin_field_centerCircleDiameter")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spin_field_centerCircleDiameter)
        self.borderStripWidthLabel = QtWidgets.QLabel(self.groupBox_2)
        self.borderStripWidthLabel.setObjectName("borderStripWidthLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.borderStripWidthLabel)
        self.spin_field_borderStripWidth = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_field_borderStripWidth.setObjectName("spin_field_borderStripWidth")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spin_field_borderStripWidth)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(4, 4, 4, 4)
        self.formLayout_3.setObjectName("formLayout_3")
        self.postDiameterLabel = QtWidgets.QLabel(self.groupBox_3)
        self.postDiameterLabel.setObjectName("postDiameterLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.postDiameterLabel)
        self.spin_goal_postDiameter = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spin_goal_postDiameter.setObjectName("spin_goal_postDiameter")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_goal_postDiameter)
        self.heightLabel = QtWidgets.QLabel(self.groupBox_3)
        self.heightLabel.setObjectName("heightLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.heightLabel)
        self.spin_goal_height = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spin_goal_height.setObjectName("spin_goal_height")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_goal_height)
        self.innerWidthLabel = QtWidgets.QLabel(self.groupBox_3)
        self.innerWidthLabel.setObjectName("innerWidthLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.innerWidthLabel)
        self.spin_goal_innerWidth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spin_goal_innerWidth.setObjectName("spin_goal_innerWidth")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_goal_innerWidth)
        self.depthLabel = QtWidgets.QLabel(self.groupBox_3)
        self.depthLabel.setObjectName("depthLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.depthLabel)
        self.spin_goal_depth = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spin_goal_depth.setObjectName("spin_goal_depth")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_goal_depth)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAccept = QtWidgets.QPushButton(FieldConfig)
        self.btnAccept.setMinimumSize(QtCore.QSize(171, 0))
        self.btnAccept.setObjectName("btnAccept")
        self.horizontalLayout.addWidget(self.btnAccept)
        self.btnDiscard = QtWidgets.QPushButton(FieldConfig)
        self.btnDiscard.setMinimumSize(QtCore.QSize(171, 0))
        self.btnDiscard.setObjectName("btnDiscard")
        self.horizontalLayout.addWidget(self.btnDiscard)
        self.btnLoadFieldType = QtWidgets.QToolButton(FieldConfig)
        self.btnLoadFieldType.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btnLoadFieldType.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.btnLoadFieldType.setObjectName("btnLoadFieldType")
        self.horizontalLayout.addWidget(self.btnLoadFieldType)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FieldConfig)
        QtCore.QMetaObject.connectSlotsByName(FieldConfig)
        FieldConfig.setTabOrder(self.nameLineEdit, self.spin_center_x)
        FieldConfig.setTabOrder(self.spin_center_x, self.spin_center_y)
        FieldConfig.setTabOrder(self.spin_center_y, self.enabledCheckBox)
        FieldConfig.setTabOrder(self.enabledCheckBox, self.spin_field_length)
        FieldConfig.setTabOrder(self.spin_field_length, self.spin_field_width)
        FieldConfig.setTabOrder(self.spin_field_width, self.spin_field_lineWidth)
        FieldConfig.setTabOrder(self.spin_field_lineWidth, self.spin_field_penaltyMarkerSize)
        FieldConfig.setTabOrder(self.spin_field_penaltyMarkerSize, self.spin_field_penaltyMarkerDistance)
        FieldConfig.setTabOrder(self.spin_field_penaltyMarkerDistance, self.spin_field_penaltyAreaLength)
        FieldConfig.setTabOrder(self.spin_field_penaltyAreaLength, self.spin_field_penaltyAreaWidth)
        FieldConfig.setTabOrder(self.spin_field_penaltyAreaWidth, self.spin_field_centerCircleDiameter)
        FieldConfig.setTabOrder(self.spin_field_centerCircleDiameter, self.spin_field_borderStripWidth)
        FieldConfig.setTabOrder(self.spin_field_borderStripWidth, self.spin_goal_postDiameter)
        FieldConfig.setTabOrder(self.spin_goal_postDiameter, self.spin_goal_height)
        FieldConfig.setTabOrder(self.spin_goal_height, self.spin_goal_innerWidth)
        FieldConfig.setTabOrder(self.spin_goal_innerWidth, self.spin_goal_depth)
        FieldConfig.setTabOrder(self.spin_goal_depth, self.btnAccept)
        FieldConfig.setTabOrder(self.btnAccept, self.btnDiscard)
        FieldConfig.setTabOrder(self.btnDiscard, self.btnLoadFieldType)
        FieldConfig.setTabOrder(self.btnLoadFieldType, self.scrollArea)

    def retranslateUi(self, FieldConfig):
        _translate = QtCore.QCoreApplication.translate
        FieldConfig.setWindowTitle(_translate("FieldConfig", "Form"))
        self.groupBox.setTitle(_translate("FieldConfig", "General:"))
        self.nameLabel.setText(_translate("FieldConfig", "Name:"))
        self.centerLabel.setText(_translate("FieldConfig", "Center:"))
        self.label_center_x.setText(_translate("FieldConfig", "X:"))
        self.label_center_y.setText(_translate("FieldConfig", "Y:"))
        self.enabledLabel.setText(_translate("FieldConfig", "Enabled:"))
        self.groupBox_2.setTitle(_translate("FieldConfig", "Field:"))
        self.dimensionLabel.setText(_translate("FieldConfig", "Dimension:"))
        self.label_length.setText(_translate("FieldConfig", "Length:"))
        self.label_width.setText(_translate("FieldConfig", "Width:"))
        self.lineWidthLabel.setText(_translate("FieldConfig", "lineWidth:"))
        self.penaltyMarkerLabel.setText(_translate("FieldConfig", "penaltyMarker:"))
        self.label_length_2.setText(_translate("FieldConfig", "Size:"))
        self.label_width_2.setText(_translate("FieldConfig", "Distance:"))
        self.penaltyAreaLabel.setText(_translate("FieldConfig", "penaltyArea"))
        self.label_length_3.setText(_translate("FieldConfig", "Length:"))
        self.label_width_3.setText(_translate("FieldConfig", "Width:"))
        self.centerCircleDiameterLabel.setText(_translate("FieldConfig", "centerCircleDiameter:"))
        self.borderStripWidthLabel.setText(_translate("FieldConfig", "borderStripWidth"))
        self.groupBox_3.setTitle(_translate("FieldConfig", "Goal:"))
        self.postDiameterLabel.setText(_translate("FieldConfig", "postDiameter"))
        self.heightLabel.setText(_translate("FieldConfig", "height"))
        self.innerWidthLabel.setText(_translate("FieldConfig", "innerWidth"))
        self.depthLabel.setText(_translate("FieldConfig", "depth"))
        self.btnAccept.setText(_translate("FieldConfig", "Accept"))
        self.btnDiscard.setText(_translate("FieldConfig", "Discard"))
        self.btnLoadFieldType.setText(_translate("FieldConfig", "Load"))

