# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mate/ui/views/map/layer/obstacleData_config_view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ObstacleDataConfig(object):
    def setupUi(self, ObstacleDataConfig):
        ObstacleDataConfig.setObjectName("ObstacleDataConfig")
        ObstacleDataConfig.resize(591, 613)
        self.verticalLayout = QtWidgets.QVBoxLayout(ObstacleDataConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(ObstacleDataConfig)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -467, 559, 1026))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(4, 4, 4, 4)
        self.formLayout.setObjectName("formLayout")
        self.nameObstacleDataEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nameObstacleDataEdit.setObjectName("nameObstacleDataEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameObstacleDataEdit)
        self.centerLabel = QtWidgets.QLabel(self.groupBox)
        self.centerLabel.setObjectName("centerLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.centerLabel)
        self.centerWidget = QtWidgets.QWidget(self.groupBox)
        self.centerWidget.setObjectName("centerWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centerWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_center_x = QtWidgets.QLabel(self.centerWidget)
        self.label_center_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_x.setObjectName("label_center_x")
        self.horizontalLayout_2.addWidget(self.label_center_x)
        self.spin_center_x = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_x.setMinimum(-99.99)
        self.spin_center_x.setObjectName("spin_center_x")
        self.horizontalLayout_2.addWidget(self.spin_center_x)
        self.label_center_y = QtWidgets.QLabel(self.centerWidget)
        self.label_center_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_y.setObjectName("label_center_y")
        self.horizontalLayout_2.addWidget(self.label_center_y)
        self.spin_center_y = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_y.setMinimum(-99.99)
        self.spin_center_y.setObjectName("spin_center_y")
        self.horizontalLayout_2.addWidget(self.spin_center_y)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.centerWidget)
        self.enabledLabel = QtWidgets.QLabel(self.groupBox)
        self.enabledLabel.setObjectName("enabledLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.enabledLabel)
        self.enabledCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.enabledCheckBox.setChecked(True)
        self.enabledCheckBox.setObjectName("enabledCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.enabledCheckBox)
        self.nameLabel = QtWidgets.QLabel(self.groupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.translationLabel = QtWidgets.QLabel(self.groupBox)
        self.translationLabel.setObjectName("translationLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.translationLabel)
        self.translationWidget = QtWidgets.QWidget(self.groupBox)
        self.translationWidget.setObjectName("translationWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.translationWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cbx_TransformationKey = QtWidgets.QComboBox(self.translationWidget)
        self.cbx_TransformationKey.setEditable(True)
        self.cbx_TransformationKey.setObjectName("cbx_TransformationKey")
        self.verticalLayout_6.addWidget(self.cbx_TransformationKey)
        self.label_4 = QtWidgets.QLabel(self.translationWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.edit_TransformationKeyLambda = QtWidgets.QTextEdit(self.translationWidget)
        self.edit_TransformationKeyLambda.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_TransformationKeyLambda.setTabStopWidth(16)
        self.edit_TransformationKeyLambda.setObjectName("edit_TransformationKeyLambda")
        self.verticalLayout_6.addWidget(self.edit_TransformationKeyLambda)
        self.label_3 = QtWidgets.QLabel(self.translationWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.translationWidget)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(4, 4, 4, 4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.KeyLabel = QtWidgets.QLabel(self.groupBox_2)
        self.KeyLabel.setObjectName("KeyLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.KeyLabel)
        self.keyLambdaWidget = QtWidgets.QWidget(self.groupBox_2)
        self.keyLambdaWidget.setObjectName("keyLambdaWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.keyLambdaWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbx_ObstacleDataKey = QtWidgets.QComboBox(self.keyLambdaWidget)
        self.cbx_ObstacleDataKey.setEditable(True)
        self.cbx_ObstacleDataKey.setObjectName("cbx_ObstacleDataKey")
        self.verticalLayout_4.addWidget(self.cbx_ObstacleDataKey)
        self.label = QtWidgets.QLabel(self.keyLambdaWidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.edit_ObstacleDataKeyLambda = QtWidgets.QTextEdit(self.keyLambdaWidget)
        self.edit_ObstacleDataKeyLambda.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_ObstacleDataKeyLambda.setTabStopWidth(16)
        self.edit_ObstacleDataKeyLambda.setObjectName("edit_ObstacleDataKeyLambda")
        self.verticalLayout_4.addWidget(self.edit_ObstacleDataKeyLambda)
        self.label_2 = QtWidgets.QLabel(self.keyLambdaWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.keyLambdaWidget)
        self.goalPostColorWidget = QtWidgets.QWidget(self.groupBox_2)
        self.goalPostColorWidget.setObjectName("goalPostColorWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.goalPostColorWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.edit_unknownColor = QtWidgets.QLineEdit(self.goalPostColorWidget)
        self.edit_unknownColor.setObjectName("edit_unknownColor")
        self.gridLayout.addWidget(self.edit_unknownColor, 1, 1, 1, 1)
        self.btn_teamRobotColor = QtWidgets.QPushButton(self.goalPostColorWidget)
        self.btn_teamRobotColor.setFlat(False)
        self.btn_teamRobotColor.setObjectName("btn_teamRobotColor")
        self.gridLayout.addWidget(self.btn_teamRobotColor, 4, 2, 1, 1)
        self.edit_anonymousRobotColor = QtWidgets.QLineEdit(self.goalPostColorWidget)
        self.edit_anonymousRobotColor.setObjectName("edit_anonymousRobotColor")
        self.gridLayout.addWidget(self.edit_anonymousRobotColor, 2, 1, 1, 1)
        self.btn_fallenAnonymousRobotColor = QtWidgets.QPushButton(self.goalPostColorWidget)
        self.btn_fallenAnonymousRobotColor.setFlat(False)
        self.btn_fallenAnonymousRobotColor.setObjectName("btn_fallenAnonymousRobotColor")
        self.gridLayout.addWidget(self.btn_fallenAnonymousRobotColor, 5, 2, 1, 1)
        self.edit_fallenAnonymousRobotColor = QtWidgets.QLineEdit(self.goalPostColorWidget)
        self.edit_fallenAnonymousRobotColor.setObjectName("edit_fallenAnonymousRobotColor")
        self.gridLayout.addWidget(self.edit_fallenAnonymousRobotColor, 5, 1, 1, 1)
        self.unknownColorLabel = QtWidgets.QLabel(self.goalPostColorWidget)
        self.unknownColorLabel.setObjectName("unknownColorLabel")
        self.gridLayout.addWidget(self.unknownColorLabel, 1, 0, 1, 1)
        self.fallenHostileRobotColorLabel = QtWidgets.QLabel(self.goalPostColorWidget)
        self.fallenHostileRobotColorLabel.setObjectName("fallenHostileRobotColorLabel")
        self.gridLayout.addWidget(self.fallenHostileRobotColorLabel, 6, 0, 1, 1)
        self.btn_ballColor = QtWidgets.QPushButton(self.goalPostColorWidget)
        self.btn_ballColor.setFlat(False)
        self.btn_ballColor.setObjectName("btn_ballColor")
        self.gridLayout.addWidget(self.btn_ballColor, 8, 2, 1, 1)
        self.edit_goalPostColor = QtWidgets.QLineEdit(self.goalPostColorWidget)
        self.edit_goalPostColor.setObjectName("edit_goalPostColor")
        self.gridLayout.addWidget(self.edit_goalPostColor, 0, 1, 1, 1)
        self.btn_goalPostColor = QtWidgets.QPushButton(self.goalPostColorWidget)
        self.btn_goalPostColor.setFlat(False)
        self.btn_goalPostColor.setObjectName("btn_goalPostColor")
        self.gridLayout.addWidget(self.btn_goalPostColor, 0, 2, 1, 1)
        self.btn_fallenTeamRobotColor = QtWidgets.QPushButton(self.goalPostColorWidget)
        self.btn_fallenTeamRobotColor.setFlat(False)
        self.btn_fallenTeamRobotColor.setObjectName("btn_fallenTeamRobotColor")
        self.gridLayout.addWidget(self.btn_fallenTeamRobotColor, 7, 2, 1, 1)
        self.edit_fallenTeamRobotColor = QtWidgets.QLineEdit(self.goalPostColorWidget)
        self.edit_fallenTeamRobotColor.setObjectName("edit_fallenTeamRobotColor")
        self.gridLayout.addWidget(self.edit_fallenTeamRobotColor, 7, 1, 1, 1)
        self.fallenAnonymousRobotColorLabel = QtWidgets.QLabel(self.goalPostColorWidget)
        self.fallenAnonymousRobotColorLabel.setObjectName("fallenAnonymousRobotColorLabel")
        self.gridLayout.addWidget(self.fallenAnonymousRobotColorLabel, 5, 0, 1, 1)
        self.ballColorLabel = QtWidgets.QLabel(self.goalPostColorWidget)
        self.ballColorLabel.setObjectName("ballColorLabel")
        self.gridLayout.addWidget(self.ballColorLabel, 8, 0, 1, 1)
        self.btn_fallenHostileRobotColor = QtWidgets.QPushButton(self.goalPostColorWidget)
        self.btn_fallenHostileRobotColor.setFlat(False)
        self.btn_fallenHostileRobotColor.setObjectName("btn_fallenHostileRobotColor")
        self.gridLayout.addWidget(self.btn_fallenHostileRobotColor, 6, 2, 1, 1)
        self.goalPostColorLabel = QtWidgets.QLabel(self.goalPostColorWidget)
        self.goalPostColorLabel.setObjectName("goalPostColorLabel")
        self.gridLayout.addWidget(self.goalPostColorLabel, 0, 0, 1, 1)
        self.edit_fallenHostileRobotColor = QtWidgets.QLineEdit(self.goalPostColorWidget)
        self.edit_fallenHostileRobotColor.setObjectName("edit_fallenHostileRobotColor")
        self.gridLayout.addWidget(self.edit_fallenHostileRobotColor, 6, 1, 1, 1)
        self.edit_ballColor = QtWidgets.QLineEdit(self.goalPostColorWidget)
        self.edit_ballColor.setObjectName("edit_ballColor")
        self.gridLayout.addWidget(self.edit_ballColor, 8, 1, 1, 1)
        self.btn_unknownColor = QtWidgets.QPushButton(self.goalPostColorWidget)
        self.btn_unknownColor.setFlat(False)
        self.btn_unknownColor.setObjectName("btn_unknownColor")
        self.gridLayout.addWidget(self.btn_unknownColor, 1, 2, 1, 1)
        self.teamRobotColorLabel = QtWidgets.QLabel(self.goalPostColorWidget)
        self.teamRobotColorLabel.setObjectName("teamRobotColorLabel")
        self.gridLayout.addWidget(self.teamRobotColorLabel, 4, 0, 1, 1)
        self.btn_anonymousRobotColor = QtWidgets.QPushButton(self.goalPostColorWidget)
        self.btn_anonymousRobotColor.setFlat(False)
        self.btn_anonymousRobotColor.setObjectName("btn_anonymousRobotColor")
        self.gridLayout.addWidget(self.btn_anonymousRobotColor, 2, 2, 1, 1)
        self.fallenTeamRobotColorLabel = QtWidgets.QLabel(self.goalPostColorWidget)
        self.fallenTeamRobotColorLabel.setObjectName("fallenTeamRobotColorLabel")
        self.gridLayout.addWidget(self.fallenTeamRobotColorLabel, 7, 0, 1, 1)
        self.hostileRobotColorLabel = QtWidgets.QLabel(self.goalPostColorWidget)
        self.hostileRobotColorLabel.setObjectName("hostileRobotColorLabel")
        self.gridLayout.addWidget(self.hostileRobotColorLabel, 3, 0, 1, 1)
        self.edit_hostileRobotColor = QtWidgets.QLineEdit(self.goalPostColorWidget)
        self.edit_hostileRobotColor.setObjectName("edit_hostileRobotColor")
        self.gridLayout.addWidget(self.edit_hostileRobotColor, 3, 1, 1, 1)
        self.edit_teamRobotColor = QtWidgets.QLineEdit(self.goalPostColorWidget)
        self.edit_teamRobotColor.setObjectName("edit_teamRobotColor")
        self.gridLayout.addWidget(self.edit_teamRobotColor, 4, 1, 1, 1)
        self.anonymousRobotColorLabel = QtWidgets.QLabel(self.goalPostColorWidget)
        self.anonymousRobotColorLabel.setObjectName("anonymousRobotColorLabel")
        self.gridLayout.addWidget(self.anonymousRobotColorLabel, 2, 0, 1, 1)
        self.btn_hostileRobotColor = QtWidgets.QPushButton(self.goalPostColorWidget)
        self.btn_hostileRobotColor.setFlat(False)
        self.btn_hostileRobotColor.setObjectName("btn_hostileRobotColor")
        self.gridLayout.addWidget(self.btn_hostileRobotColor, 3, 2, 1, 1)
        self.teamRobotColorWidget = QtWidgets.QWidget(self.goalPostColorWidget)
        self.teamRobotColorWidget.setObjectName("teamRobotColorWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.teamRobotColorWidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout.addWidget(self.teamRobotColorWidget, 11, 2, 1, 1)
        self.edit_freeKickAreaColor = QtWidgets.QLineEdit(self.goalPostColorWidget)
        self.edit_freeKickAreaColor.setObjectName("edit_freeKickAreaColor")
        self.gridLayout.addWidget(self.edit_freeKickAreaColor, 9, 1, 1, 1)
        self.freeKickAreaColorLabel = QtWidgets.QLabel(self.goalPostColorWidget)
        self.freeKickAreaColorLabel.setObjectName("freeKickAreaColorLabel")
        self.gridLayout.addWidget(self.freeKickAreaColorLabel, 9, 0, 1, 1)
        self.btn_freeKickAreaColor = QtWidgets.QPushButton(self.goalPostColorWidget)
        self.btn_freeKickAreaColor.setFlat(False)
        self.btn_freeKickAreaColor.setObjectName("btn_freeKickAreaColor")
        self.gridLayout.addWidget(self.btn_freeKickAreaColor, 9, 2, 1, 1)
        self.penWidth = QtWidgets.QLabel(self.goalPostColorWidget)
        self.penWidth.setObjectName("penWidth")
        self.gridLayout.addWidget(self.penWidth, 11, 0, 1, 1)
        self.spin_penWidth = QtWidgets.QDoubleSpinBox(self.goalPostColorWidget)
        self.spin_penWidth.setObjectName("spin_penWidth")
        self.gridLayout.addWidget(self.spin_penWidth, 11, 1, 1, 1)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.goalPostColorWidget)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAccept = QtWidgets.QPushButton(ObstacleDataConfig)
        self.btnAccept.setObjectName("btnAccept")
        self.horizontalLayout.addWidget(self.btnAccept)
        self.btnDiscard = QtWidgets.QPushButton(ObstacleDataConfig)
        self.btnDiscard.setObjectName("btnDiscard")
        self.horizontalLayout.addWidget(self.btnDiscard)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ObstacleDataConfig)
        QtCore.QMetaObject.connectSlotsByName(ObstacleDataConfig)
        ObstacleDataConfig.setTabOrder(self.nameObstacleDataEdit, self.spin_center_x)
        ObstacleDataConfig.setTabOrder(self.spin_center_x, self.spin_center_y)
        ObstacleDataConfig.setTabOrder(self.spin_center_y, self.enabledCheckBox)
        ObstacleDataConfig.setTabOrder(self.enabledCheckBox, self.edit_ObstacleDataKeyLambda)
        ObstacleDataConfig.setTabOrder(self.edit_ObstacleDataKeyLambda, self.edit_goalPostColor)
        ObstacleDataConfig.setTabOrder(self.edit_goalPostColor, self.btnAccept)
        ObstacleDataConfig.setTabOrder(self.btnAccept, self.btnDiscard)
        ObstacleDataConfig.setTabOrder(self.btnDiscard, self.scrollArea)

    def retranslateUi(self, ObstacleDataConfig):
        _translate = QtCore.QCoreApplication.translate
        ObstacleDataConfig.setWindowTitle(_translate("ObstacleDataConfig", "Form"))
        self.groupBox.setTitle(_translate("ObstacleDataConfig", "General:"))
        self.centerLabel.setText(_translate("ObstacleDataConfig", "Center"))
        self.label_center_x.setText(_translate("ObstacleDataConfig", "X:"))
        self.label_center_y.setText(_translate("ObstacleDataConfig", "Y:"))
        self.enabledLabel.setText(_translate("ObstacleDataConfig", "Enabled:"))
        self.nameLabel.setText(_translate("ObstacleDataConfig", "Name:"))
        self.translationLabel.setText(_translate("ObstacleDataConfig", "TransformationKey:"))
        self.label_4.setText(_translate("ObstacleDataConfig", "def parse(input):"))
        self.label_3.setText(_translate("ObstacleDataConfig", "return output"))
        self.groupBox_2.setTitle(_translate("ObstacleDataConfig", "Obstacles:"))
        self.KeyLabel.setText(_translate("ObstacleDataConfig", "Key:"))
        self.label.setText(_translate("ObstacleDataConfig", "def parse(input):"))
        self.label_2.setText(_translate("ObstacleDataConfig", "return output"))
        self.btn_teamRobotColor.setText(_translate("ObstacleDataConfig", "Pick"))
        self.btn_fallenAnonymousRobotColor.setText(_translate("ObstacleDataConfig", "Pick"))
        self.unknownColorLabel.setText(_translate("ObstacleDataConfig", "unknown:"))
        self.fallenHostileRobotColorLabel.setText(_translate("ObstacleDataConfig", "fallenHostileRobot:"))
        self.btn_ballColor.setText(_translate("ObstacleDataConfig", "Pick"))
        self.btn_goalPostColor.setText(_translate("ObstacleDataConfig", "Pick"))
        self.btn_fallenTeamRobotColor.setText(_translate("ObstacleDataConfig", "Pick"))
        self.fallenAnonymousRobotColorLabel.setText(_translate("ObstacleDataConfig", "fallenAnonymousRobot:"))
        self.ballColorLabel.setText(_translate("ObstacleDataConfig", "ball:"))
        self.btn_fallenHostileRobotColor.setText(_translate("ObstacleDataConfig", "Pick"))
        self.goalPostColorLabel.setText(_translate("ObstacleDataConfig", "goalPost:"))
        self.btn_unknownColor.setText(_translate("ObstacleDataConfig", "Pick"))
        self.teamRobotColorLabel.setText(_translate("ObstacleDataConfig", "teamRobot:"))
        self.btn_anonymousRobotColor.setText(_translate("ObstacleDataConfig", "Pick"))
        self.fallenTeamRobotColorLabel.setText(_translate("ObstacleDataConfig", "fallenTeamRobot:"))
        self.hostileRobotColorLabel.setText(_translate("ObstacleDataConfig", "hostileRobot:"))
        self.anonymousRobotColorLabel.setText(_translate("ObstacleDataConfig", "anonymousRobot:"))
        self.btn_hostileRobotColor.setText(_translate("ObstacleDataConfig", "Pick"))
        self.freeKickAreaColorLabel.setText(_translate("ObstacleDataConfig", "freeKickArea:"))
        self.btn_freeKickAreaColor.setText(_translate("ObstacleDataConfig", "Pick"))
        self.penWidth.setText(_translate("ObstacleDataConfig", "penWidth:"))
        self.btnAccept.setText(_translate("ObstacleDataConfig", "Accept"))
        self.btnDiscard.setText(_translate("ObstacleDataConfig", "Discard"))

