# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mate/ui/views/map/layer/pose_config_view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PoseConfig(object):
    def setupUi(self, PoseConfig):
        PoseConfig.setObjectName("PoseConfig")
        PoseConfig.resize(477, 689)
        self.verticalLayout = QtWidgets.QVBoxLayout(PoseConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(PoseConfig)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -355, 445, 996))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(4, 4, 4, 4)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.groupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.centerLabel = QtWidgets.QLabel(self.groupBox)
        self.centerLabel.setObjectName("centerLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.centerLabel)
        self.centerWidget = QtWidgets.QWidget(self.groupBox)
        self.centerWidget.setObjectName("centerWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centerWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_center_x = QtWidgets.QLabel(self.centerWidget)
        self.label_center_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_x.setObjectName("label_center_x")
        self.horizontalLayout_2.addWidget(self.label_center_x)
        self.spin_center_x = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_x.setMinimum(-99.99)
        self.spin_center_x.setObjectName("spin_center_x")
        self.horizontalLayout_2.addWidget(self.spin_center_x)
        self.label_center_y = QtWidgets.QLabel(self.centerWidget)
        self.label_center_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_y.setObjectName("label_center_y")
        self.horizontalLayout_2.addWidget(self.label_center_y)
        self.spin_center_y = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_y.setMinimum(-99.99)
        self.spin_center_y.setObjectName("spin_center_y")
        self.horizontalLayout_2.addWidget(self.spin_center_y)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.centerWidget)
        self.translationLabel = QtWidgets.QLabel(self.groupBox)
        self.translationLabel.setObjectName("translationLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.translationLabel)
        self.translationWidget = QtWidgets.QWidget(self.groupBox)
        self.translationWidget.setObjectName("translationWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.translationWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cbx_TransformationKey = QtWidgets.QComboBox(self.translationWidget)
        self.cbx_TransformationKey.setEditable(True)
        self.cbx_TransformationKey.setObjectName("cbx_TransformationKey")
        self.verticalLayout_6.addWidget(self.cbx_TransformationKey)
        self.label_4 = QtWidgets.QLabel(self.translationWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.edit_TransformationKeyLambda = QtWidgets.QTextEdit(self.translationWidget)
        self.edit_TransformationKeyLambda.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_TransformationKeyLambda.setTabStopWidth(16)
        self.edit_TransformationKeyLambda.setObjectName("edit_TransformationKeyLambda")
        self.verticalLayout_6.addWidget(self.edit_TransformationKeyLambda)
        self.label_3 = QtWidgets.QLabel(self.translationWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.translationWidget)
        self.enabledLabel = QtWidgets.QLabel(self.groupBox)
        self.enabledLabel.setObjectName("enabledLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.enabledLabel)
        self.enabledCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.enabledCheckBox.setChecked(True)
        self.enabledCheckBox.setObjectName("enabledCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.enabledCheckBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(4, 4, 4, 4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.positionCircleDiameterLabel = QtWidgets.QLabel(self.groupBox_2)
        self.positionCircleDiameterLabel.setObjectName("positionCircleDiameterLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.positionCircleDiameterLabel)
        self.spin_positionCircleDiameter = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_positionCircleDiameter.setObjectName("spin_positionCircleDiameter")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_positionCircleDiameter)
        self.orientationLineLengthLabel = QtWidgets.QLabel(self.groupBox_2)
        self.orientationLineLengthLabel.setObjectName("orientationLineLengthLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.orientationLineLengthLabel)
        self.spin_orientationLineLength = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_orientationLineLength.setObjectName("spin_orientationLineLength")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_orientationLineLength)
        self.poseColorWidget = QtWidgets.QWidget(self.groupBox_2)
        self.poseColorWidget.setObjectName("poseColorWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.poseColorWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.poseColorLabel = QtWidgets.QLabel(self.poseColorWidget)
        self.poseColorLabel.setObjectName("poseColorLabel")
        self.horizontalLayout_3.addWidget(self.poseColorLabel)
        self.edit_poseColor = QtWidgets.QLineEdit(self.poseColorWidget)
        self.edit_poseColor.setObjectName("edit_poseColor")
        self.horizontalLayout_3.addWidget(self.edit_poseColor)
        self.btn_poseColor = QtWidgets.QPushButton(self.poseColorWidget)
        self.btn_poseColor.setFlat(False)
        self.btn_poseColor.setObjectName("btn_poseColor")
        self.horizontalLayout_3.addWidget(self.btn_poseColor)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.poseColorWidget)
        self.poseKeyLambdaWidget = QtWidgets.QWidget(self.groupBox_2)
        self.poseKeyLambdaWidget.setObjectName("poseKeyLambdaWidget")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.poseKeyLambdaWidget)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.cbx_PoseKey = QtWidgets.QComboBox(self.poseKeyLambdaWidget)
        self.cbx_PoseKey.setEditable(True)
        self.cbx_PoseKey.setObjectName("cbx_PoseKey")
        self.verticalLayout_61.addWidget(self.cbx_PoseKey)
        self.label = QtWidgets.QLabel(self.poseKeyLambdaWidget)
        self.label.setObjectName("label")
        self.verticalLayout_61.addWidget(self.label)
        self.edit_poseKeyLambda = QtWidgets.QTextEdit(self.poseKeyLambdaWidget)
        self.edit_poseKeyLambda.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_poseKeyLambda.setObjectName("edit_poseKeyLambda")
        self.verticalLayout_61.addWidget(self.edit_poseKeyLambda)
        self.label_2 = QtWidgets.QLabel(self.poseKeyLambdaWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_61.addWidget(self.label_2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.poseKeyLambdaWidget)
        self.poseKeyLabel = QtWidgets.QLabel(self.groupBox_2)
        self.poseKeyLabel.setObjectName("poseKeyLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.poseKeyLabel)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(4, 4, 4, 4)
        self.formLayout_3.setObjectName("formLayout_3")
        self.maxDistanceLabel = QtWidgets.QLabel(self.groupBox_3)
        self.maxDistanceLabel.setObjectName("maxDistanceLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.maxDistanceLabel)
        self.spin_maxDistance = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spin_maxDistance.setObjectName("spin_maxDistance")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_maxDistance)
        self.cameraOpeningAngleLabel = QtWidgets.QLabel(self.groupBox_3)
        self.cameraOpeningAngleLabel.setObjectName("cameraOpeningAngleLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.cameraOpeningAngleLabel)
        self.spin_cameraOpeningAngle = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spin_cameraOpeningAngle.setObjectName("spin_cameraOpeningAngle")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_cameraOpeningAngle)
        self.jointSensorDataKeyLambdaWidget = QtWidgets.QWidget(self.groupBox_3)
        self.jointSensorDataKeyLambdaWidget.setObjectName("jointSensorDataKeyLambdaWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.jointSensorDataKeyLambdaWidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.cbx_JointSensorDataKey = QtWidgets.QComboBox(self.jointSensorDataKeyLambdaWidget)
        self.cbx_JointSensorDataKey.setEditable(True)
        self.cbx_JointSensorDataKey.setObjectName("cbx_JointSensorDataKey")
        self.verticalLayout_7.addWidget(self.cbx_JointSensorDataKey)
        self.label_31 = QtWidgets.QLabel(self.jointSensorDataKeyLambdaWidget)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_7.addWidget(self.label_31)
        self.edit_jointSensorDataKeyLambda = QtWidgets.QTextEdit(self.jointSensorDataKeyLambdaWidget)
        self.edit_jointSensorDataKeyLambda.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_jointSensorDataKeyLambda.setObjectName("edit_jointSensorDataKeyLambda")
        self.verticalLayout_7.addWidget(self.edit_jointSensorDataKeyLambda)
        self.label_41 = QtWidgets.QLabel(self.jointSensorDataKeyLambdaWidget)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_7.addWidget(self.label_41)
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.jointSensorDataKeyLambdaWidget)
        self.poseKeyLabel_2 = QtWidgets.QLabel(self.groupBox_3)
        self.poseKeyLabel_2.setObjectName("poseKeyLabel_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.poseKeyLabel_2)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAccept = QtWidgets.QPushButton(PoseConfig)
        self.btnAccept.setObjectName("btnAccept")
        self.horizontalLayout.addWidget(self.btnAccept)
        self.btnDiscard = QtWidgets.QPushButton(PoseConfig)
        self.btnDiscard.setObjectName("btnDiscard")
        self.horizontalLayout.addWidget(self.btnDiscard)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PoseConfig)
        QtCore.QMetaObject.connectSlotsByName(PoseConfig)
        PoseConfig.setTabOrder(self.nameLineEdit, self.spin_center_x)
        PoseConfig.setTabOrder(self.spin_center_x, self.spin_center_y)
        PoseConfig.setTabOrder(self.spin_center_y, self.enabledCheckBox)
        PoseConfig.setTabOrder(self.enabledCheckBox, self.edit_poseKeyLambda)
        PoseConfig.setTabOrder(self.edit_poseKeyLambda, self.spin_positionCircleDiameter)
        PoseConfig.setTabOrder(self.spin_positionCircleDiameter, self.spin_orientationLineLength)
        PoseConfig.setTabOrder(self.spin_orientationLineLength, self.edit_jointSensorDataKeyLambda)
        PoseConfig.setTabOrder(self.edit_jointSensorDataKeyLambda, self.spin_maxDistance)
        PoseConfig.setTabOrder(self.spin_maxDistance, self.spin_cameraOpeningAngle)
        PoseConfig.setTabOrder(self.spin_cameraOpeningAngle, self.btnAccept)
        PoseConfig.setTabOrder(self.btnAccept, self.btnDiscard)
        PoseConfig.setTabOrder(self.btnDiscard, self.scrollArea)

    def retranslateUi(self, PoseConfig):
        _translate = QtCore.QCoreApplication.translate
        PoseConfig.setWindowTitle(_translate("PoseConfig", "Form"))
        self.groupBox.setTitle(_translate("PoseConfig", "General:"))
        self.nameLabel.setText(_translate("PoseConfig", "Name:"))
        self.centerLabel.setText(_translate("PoseConfig", "Center"))
        self.label_center_x.setText(_translate("PoseConfig", "X:"))
        self.label_center_y.setText(_translate("PoseConfig", "Y:"))
        self.translationLabel.setText(_translate("PoseConfig", "TransformationKey:"))
        self.label_4.setText(_translate("PoseConfig", "def parse(input):"))
        self.label_3.setText(_translate("PoseConfig", "return output"))
        self.enabledLabel.setText(_translate("PoseConfig", "Enabled:"))
        self.groupBox_2.setTitle(_translate("PoseConfig", "Pose:"))
        self.positionCircleDiameterLabel.setText(_translate("PoseConfig", "positionCircleDiameter:"))
        self.orientationLineLengthLabel.setText(_translate("PoseConfig", "orientationLineLength"))
        self.poseColorLabel.setText(_translate("PoseConfig", "Color:"))
        self.btn_poseColor.setText(_translate("PoseConfig", "Pick"))
        self.label.setText(_translate("PoseConfig", "def parse(input):"))
        self.label_2.setText(_translate("PoseConfig", "return output"))
        self.poseKeyLabel.setText(_translate("PoseConfig", "Key:"))
        self.groupBox_3.setTitle(_translate("PoseConfig", "FOV:"))
        self.maxDistanceLabel.setText(_translate("PoseConfig", "maxDistance"))
        self.cameraOpeningAngleLabel.setText(_translate("PoseConfig", "cameraOpeningAngle"))
        self.label_31.setText(_translate("PoseConfig", "def parse(input):"))
        self.label_41.setText(_translate("PoseConfig", "return output"))
        self.poseKeyLabel_2.setText(_translate("PoseConfig", "JointSensorDataKey:"))
        self.btnAccept.setText(_translate("PoseConfig", "Accept"))
        self.btnDiscard.setText(_translate("PoseConfig", "Discard"))

