# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mate/ui/views/map/layer/sonarSensors_config_view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SonarSensorsConfig(object):
    def setupUi(self, SonarSensorsConfig):
        SonarSensorsConfig.setObjectName("SonarSensorsConfig")
        SonarSensorsConfig.resize(591, 613)
        self.verticalLayout = QtWidgets.QVBoxLayout(SonarSensorsConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(SonarSensorsConfig)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -89, 559, 654))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(4, 4, 4, 4)
        self.formLayout.setObjectName("formLayout")
        self.nameSonarEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nameSonarEdit.setObjectName("nameSonarEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameSonarEdit)
        self.centerLabel = QtWidgets.QLabel(self.groupBox)
        self.centerLabel.setObjectName("centerLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.centerLabel)
        self.centerWidget = QtWidgets.QWidget(self.groupBox)
        self.centerWidget.setObjectName("centerWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centerWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_center_x = QtWidgets.QLabel(self.centerWidget)
        self.label_center_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_x.setObjectName("label_center_x")
        self.horizontalLayout_2.addWidget(self.label_center_x)
        self.spin_center_x = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_x.setMinimum(-99.99)
        self.spin_center_x.setObjectName("spin_center_x")
        self.horizontalLayout_2.addWidget(self.spin_center_x)
        self.label_center_y = QtWidgets.QLabel(self.centerWidget)
        self.label_center_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_y.setObjectName("label_center_y")
        self.horizontalLayout_2.addWidget(self.label_center_y)
        self.spin_center_y = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_y.setMinimum(-99.99)
        self.spin_center_y.setObjectName("spin_center_y")
        self.horizontalLayout_2.addWidget(self.spin_center_y)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.centerWidget)
        self.enabledLabel = QtWidgets.QLabel(self.groupBox)
        self.enabledLabel.setObjectName("enabledLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.enabledLabel)
        self.enabledCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.enabledCheckBox.setChecked(True)
        self.enabledCheckBox.setObjectName("enabledCheckBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.enabledCheckBox)
        self.nameLabel = QtWidgets.QLabel(self.groupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.translationLabel = QtWidgets.QLabel(self.groupBox)
        self.translationLabel.setObjectName("translationLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.translationLabel)
        self.translationWidget = QtWidgets.QWidget(self.groupBox)
        self.translationWidget.setObjectName("translationWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.translationWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cbx_TransformationKey = QtWidgets.QComboBox(self.translationWidget)
        self.cbx_TransformationKey.setEditable(True)
        self.cbx_TransformationKey.setObjectName("cbx_TransformationKey")
        self.verticalLayout_6.addWidget(self.cbx_TransformationKey)
        self.label_4 = QtWidgets.QLabel(self.translationWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.edit_TransformationKeyLambda = QtWidgets.QTextEdit(self.translationWidget)
        self.edit_TransformationKeyLambda.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_TransformationKeyLambda.setTabStopWidth(16)
        self.edit_TransformationKeyLambda.setObjectName("edit_TransformationKeyLambda")
        self.verticalLayout_6.addWidget(self.edit_TransformationKeyLambda)
        self.label_3 = QtWidgets.QLabel(self.translationWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.translationWidget)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(4, 4, 4, 4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.KeyLabel = QtWidgets.QLabel(self.groupBox_2)
        self.KeyLabel.setObjectName("KeyLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.KeyLabel)
        self.keyLambdaWidget = QtWidgets.QWidget(self.groupBox_2)
        self.keyLambdaWidget.setObjectName("keyLambdaWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.keyLambdaWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cbx_RawSonarKey = QtWidgets.QComboBox(self.keyLambdaWidget)
        self.cbx_RawSonarKey.setEditable(True)
        self.cbx_RawSonarKey.setObjectName("cbx_RawSonarKey")
        self.verticalLayout_4.addWidget(self.cbx_RawSonarKey)
        self.label = QtWidgets.QLabel(self.keyLambdaWidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.edit_RawSonarKeyLambda = QtWidgets.QTextEdit(self.keyLambdaWidget)
        self.edit_RawSonarKeyLambda.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_RawSonarKeyLambda.setTabStopWidth(16)
        self.edit_RawSonarKeyLambda.setObjectName("edit_RawSonarKeyLambda")
        self.verticalLayout_4.addWidget(self.edit_RawSonarKeyLambda)
        self.label_2 = QtWidgets.QLabel(self.keyLambdaWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.keyLambdaWidget)
        self.KeyLabel_2 = QtWidgets.QLabel(self.groupBox_2)
        self.KeyLabel_2.setObjectName("KeyLabel_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.KeyLabel_2)
        self.keyLambdaWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.keyLambdaWidget_2.setObjectName("keyLambdaWidget_2")
        self.verticalLayout_51 = QtWidgets.QVBoxLayout(self.keyLambdaWidget_2)
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.cbx_FilteredSonarKey = QtWidgets.QComboBox(self.keyLambdaWidget_2)
        self.cbx_FilteredSonarKey.setEditable(True)
        self.cbx_FilteredSonarKey.setObjectName("cbx_FilteredSonarKey")
        self.verticalLayout_51.addWidget(self.cbx_FilteredSonarKey)
        self.label_31 = QtWidgets.QLabel(self.keyLambdaWidget_2)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_51.addWidget(self.label_31)
        self.edit_FilteredSonarKeyLambda = QtWidgets.QTextEdit(self.keyLambdaWidget_2)
        self.edit_FilteredSonarKeyLambda.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_FilteredSonarKeyLambda.setTabStopWidth(16)
        self.edit_FilteredSonarKeyLambda.setObjectName("edit_FilteredSonarKeyLambda")
        self.verticalLayout_51.addWidget(self.edit_FilteredSonarKeyLambda)
        self.label_41 = QtWidgets.QLabel(self.keyLambdaWidget_2)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_51.addWidget(self.label_41)
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.keyLambdaWidget_2)
        self.sonarOpeningAngleLabel = QtWidgets.QLabel(self.groupBox_2)
        self.sonarOpeningAngleLabel.setObjectName("sonarOpeningAngleLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.sonarOpeningAngleLabel)
        self.spin_sonarOpeningAngle = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_sonarOpeningAngle.setObjectName("spin_sonarOpeningAngle")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_sonarOpeningAngle)
        self.sonarZAngleLabel = QtWidgets.QLabel(self.groupBox_2)
        self.sonarZAngleLabel.setObjectName("sonarZAngleLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sonarZAngleLabel)
        self.spin_sonarZAngle = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_sonarZAngle.setObjectName("spin_sonarZAngle")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spin_sonarZAngle)
        self.sonarYOffsetLabel = QtWidgets.QLabel(self.groupBox_2)
        self.sonarYOffsetLabel.setObjectName("sonarYOffsetLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sonarYOffsetLabel)
        self.spin_sonarYOffset = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_sonarYOffset.setObjectName("spin_sonarYOffset")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spin_sonarYOffset)
        self.sonarColorWidget = QtWidgets.QWidget(self.groupBox_2)
        self.sonarColorWidget.setObjectName("sonarColorWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.sonarColorWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sonarColorLabel = QtWidgets.QLabel(self.sonarColorWidget)
        self.sonarColorLabel.setObjectName("sonarColorLabel")
        self.horizontalLayout_3.addWidget(self.sonarColorLabel)
        self.edit_sonarColor = QtWidgets.QLineEdit(self.sonarColorWidget)
        self.edit_sonarColor.setObjectName("edit_sonarColor")
        self.horizontalLayout_3.addWidget(self.edit_sonarColor)
        self.btn_sonarColor = QtWidgets.QPushButton(self.sonarColorWidget)
        self.btn_sonarColor.setFlat(False)
        self.btn_sonarColor.setObjectName("btn_sonarColor")
        self.horizontalLayout_3.addWidget(self.btn_sonarColor)
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.sonarColorWidget)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAccept = QtWidgets.QPushButton(SonarSensorsConfig)
        self.btnAccept.setObjectName("btnAccept")
        self.horizontalLayout.addWidget(self.btnAccept)
        self.btnDiscard = QtWidgets.QPushButton(SonarSensorsConfig)
        self.btnDiscard.setObjectName("btnDiscard")
        self.horizontalLayout.addWidget(self.btnDiscard)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SonarSensorsConfig)
        QtCore.QMetaObject.connectSlotsByName(SonarSensorsConfig)
        SonarSensorsConfig.setTabOrder(self.nameSonarEdit, self.spin_center_x)
        SonarSensorsConfig.setTabOrder(self.spin_center_x, self.spin_center_y)
        SonarSensorsConfig.setTabOrder(self.spin_center_y, self.enabledCheckBox)
        SonarSensorsConfig.setTabOrder(self.enabledCheckBox, self.spin_sonarOpeningAngle)
        SonarSensorsConfig.setTabOrder(self.spin_sonarOpeningAngle, self.spin_sonarZAngle)
        SonarSensorsConfig.setTabOrder(self.spin_sonarZAngle, self.spin_sonarYOffset)
        SonarSensorsConfig.setTabOrder(self.spin_sonarYOffset, self.edit_sonarColor)
        SonarSensorsConfig.setTabOrder(self.edit_sonarColor, self.btnAccept)
        SonarSensorsConfig.setTabOrder(self.btnAccept, self.btnDiscard)
        SonarSensorsConfig.setTabOrder(self.btnDiscard, self.scrollArea)

    def retranslateUi(self, SonarSensorsConfig):
        _translate = QtCore.QCoreApplication.translate
        SonarSensorsConfig.setWindowTitle(_translate("SonarSensorsConfig", "Form"))
        self.groupBox.setTitle(_translate("SonarSensorsConfig", "General:"))
        self.centerLabel.setText(_translate("SonarSensorsConfig", "Center"))
        self.label_center_x.setText(_translate("SonarSensorsConfig", "X:"))
        self.label_center_y.setText(_translate("SonarSensorsConfig", "Y:"))
        self.enabledLabel.setText(_translate("SonarSensorsConfig", "Enabled:"))
        self.nameLabel.setText(_translate("SonarSensorsConfig", "Name:"))
        self.translationLabel.setText(_translate("SonarSensorsConfig", "TransformationKey:"))
        self.label_4.setText(_translate("SonarSensorsConfig", "def parse(input):"))
        self.label_3.setText(_translate("SonarSensorsConfig", "return output"))
        self.groupBox_2.setTitle(_translate("SonarSensorsConfig", "Sonar:"))
        self.KeyLabel.setText(_translate("SonarSensorsConfig", "Raw Key:"))
        self.label.setText(_translate("SonarSensorsConfig", "def parse(input):"))
        self.label_2.setText(_translate("SonarSensorsConfig", "return output"))
        self.KeyLabel_2.setText(_translate("SonarSensorsConfig", "Filtered Key:"))
        self.label_31.setText(_translate("SonarSensorsConfig", "def parse(input):"))
        self.label_41.setText(_translate("SonarSensorsConfig", "return output"))
        self.sonarOpeningAngleLabel.setText(_translate("SonarSensorsConfig", "openingAngle (Deg)"))
        self.sonarZAngleLabel.setText(_translate("SonarSensorsConfig", "zAngle (Deg)"))
        self.sonarYOffsetLabel.setText(_translate("SonarSensorsConfig", "yOffset (cm)"))
        self.sonarColorLabel.setText(_translate("SonarSensorsConfig", "Color:"))
        self.btn_sonarColor.setText(_translate("SonarSensorsConfig", "Pick"))
        self.btnAccept.setText(_translate("SonarSensorsConfig", "Accept"))
        self.btnDiscard.setText(_translate("SonarSensorsConfig", "Discard"))

