# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tools/mate/src/mate/ui/views/map/layer/teamPlayers_config_view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TeamPlayersConfig(object):
    def setupUi(self, TeamPlayersConfig):
        TeamPlayersConfig.setObjectName("TeamPlayersConfig")
        TeamPlayersConfig.resize(477, 689)
        self.verticalLayout = QtWidgets.QVBoxLayout(TeamPlayersConfig)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(TeamPlayersConfig)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -333, 445, 968))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(4, 4, 4, 4)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.groupBox)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.centerLabel = QtWidgets.QLabel(self.groupBox)
        self.centerLabel.setObjectName("centerLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.centerLabel)
        self.centerWidget = QtWidgets.QWidget(self.groupBox)
        self.centerWidget.setObjectName("centerWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centerWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_center_x = QtWidgets.QLabel(self.centerWidget)
        self.label_center_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_x.setObjectName("label_center_x")
        self.horizontalLayout_2.addWidget(self.label_center_x)
        self.spin_center_x = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_x.setMinimum(-99.99)
        self.spin_center_x.setObjectName("spin_center_x")
        self.horizontalLayout_2.addWidget(self.spin_center_x)
        self.label_center_y = QtWidgets.QLabel(self.centerWidget)
        self.label_center_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_center_y.setObjectName("label_center_y")
        self.horizontalLayout_2.addWidget(self.label_center_y)
        self.spin_center_y = QtWidgets.QDoubleSpinBox(self.centerWidget)
        self.spin_center_y.setMinimum(-99.99)
        self.spin_center_y.setObjectName("spin_center_y")
        self.horizontalLayout_2.addWidget(self.spin_center_y)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.centerWidget)
        self.enabledLabel = QtWidgets.QLabel(self.groupBox)
        self.enabledLabel.setObjectName("enabledLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.enabledLabel)
        self.enabledCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.enabledCheckBox.setChecked(True)
        self.enabledCheckBox.setObjectName("enabledCheckBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.enabledCheckBox)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(4, 4, 4, 4)
        self.formLayout_2.setObjectName("formLayout_2")
        self.poseKeyLabel = QtWidgets.QLabel(self.groupBox_2)
        self.poseKeyLabel.setObjectName("poseKeyLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.poseKeyLabel)
        self.TeamPlayersKeyLambdaWidget = QtWidgets.QWidget(self.groupBox_2)
        self.TeamPlayersKeyLambdaWidget.setObjectName("TeamPlayersKeyLambdaWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.TeamPlayersKeyLambdaWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cbx_TeamPlayersKey = QtWidgets.QComboBox(self.TeamPlayersKeyLambdaWidget)
        self.cbx_TeamPlayersKey.setEditable(True)
        self.cbx_TeamPlayersKey.setObjectName("cbx_TeamPlayersKey")
        self.verticalLayout_6.addWidget(self.cbx_TeamPlayersKey)
        self.label = QtWidgets.QLabel(self.TeamPlayersKeyLambdaWidget)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.edit_TeamPlayersKeyLambda = QtWidgets.QTextEdit(self.TeamPlayersKeyLambdaWidget)
        self.edit_TeamPlayersKeyLambda.setMaximumSize(QtCore.QSize(16777215, 80))
        self.edit_TeamPlayersKeyLambda.setObjectName("edit_TeamPlayersKeyLambda")
        self.verticalLayout_6.addWidget(self.edit_TeamPlayersKeyLambda)
        self.label_2 = QtWidgets.QLabel(self.TeamPlayersKeyLambdaWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.TeamPlayersKeyLambdaWidget)
        self.playerLabel = QtWidgets.QLabel(self.groupBox_2)
        self.playerLabel.setObjectName("playerLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.playerLabel)
        self.playerCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.playerCheckbox.setChecked(True)
        self.playerCheckbox.setObjectName("playerCheckbox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.playerCheckbox)
        self.poseCircleDiameterLabel = QtWidgets.QLabel(self.groupBox_2)
        self.poseCircleDiameterLabel.setObjectName("poseCircleDiameterLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.poseCircleDiameterLabel)
        self.spin_poseCircleDiameter = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_poseCircleDiameter.setObjectName("spin_poseCircleDiameter")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spin_poseCircleDiameter)
        self.targetLabel = QtWidgets.QLabel(self.groupBox_2)
        self.targetLabel.setObjectName("targetLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.targetLabel)
        self.targetCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.targetCheckbox.setChecked(True)
        self.targetCheckbox.setObjectName("targetCheckbox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.targetCheckbox)
        self.targetCircleDiameterLabel = QtWidgets.QLabel(self.groupBox_2)
        self.targetCircleDiameterLabel.setObjectName("targetCircleDiameterLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.targetCircleDiameterLabel)
        self.spin_targetCircleDiameter = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_targetCircleDiameter.setObjectName("spin_targetCircleDiameter")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.spin_targetCircleDiameter)
        self.fovLabel = QtWidgets.QLabel(self.groupBox_2)
        self.fovLabel.setObjectName("fovLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.fovLabel)
        self.fovCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.fovCheckbox.setChecked(True)
        self.fovCheckbox.setObjectName("fovCheckbox")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.fovCheckbox)
        self.maxDistanceLabel = QtWidgets.QLabel(self.groupBox_2)
        self.maxDistanceLabel.setObjectName("maxDistanceLabel")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.maxDistanceLabel)
        self.spin_maxDistance = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_maxDistance.setObjectName("spin_maxDistance")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spin_maxDistance)
        self.cameraOpeningAngleLabel = QtWidgets.QLabel(self.groupBox_2)
        self.cameraOpeningAngleLabel.setObjectName("cameraOpeningAngleLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.cameraOpeningAngleLabel)
        self.spin_cameraOpeningAngle = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_cameraOpeningAngle.setObjectName("spin_cameraOpeningAngle")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.spin_cameraOpeningAngle)
        self.defaultColorWidget = QtWidgets.QWidget(self.groupBox_2)
        self.defaultColorWidget.setObjectName("defaultColorWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.defaultColorWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.edit_supporterColor = QtWidgets.QLineEdit(self.defaultColorWidget)
        self.edit_supporterColor.setObjectName("edit_supporterColor")
        self.gridLayout_15.addWidget(self.edit_supporterColor, 3, 1, 1, 1)
        self.keeperColorLabel = QtWidgets.QLabel(self.defaultColorWidget)
        self.keeperColorLabel.setObjectName("keeperColorLabel")
        self.gridLayout_15.addWidget(self.keeperColorLabel, 1, 0, 1, 1)
        self.btn_defaultColor = QtWidgets.QPushButton(self.defaultColorWidget)
        self.btn_defaultColor.setFlat(False)
        self.btn_defaultColor.setObjectName("btn_defaultColor")
        self.gridLayout_15.addWidget(self.btn_defaultColor, 0, 2, 1, 1)
        self.btn_keeperColor = QtWidgets.QPushButton(self.defaultColorWidget)
        self.btn_keeperColor.setFlat(False)
        self.btn_keeperColor.setObjectName("btn_keeperColor")
        self.gridLayout_15.addWidget(self.btn_keeperColor, 1, 2, 1, 1)
        self.edit_defenderColor = QtWidgets.QLineEdit(self.defaultColorWidget)
        self.edit_defenderColor.setObjectName("edit_defenderColor")
        self.gridLayout_15.addWidget(self.edit_defenderColor, 2, 1, 1, 1)
        self.edit_defaultColor = QtWidgets.QLineEdit(self.defaultColorWidget)
        self.edit_defaultColor.setObjectName("edit_defaultColor")
        self.gridLayout_15.addWidget(self.edit_defaultColor, 0, 1, 1, 1)
        self.edit_strikerColor = QtWidgets.QLineEdit(self.defaultColorWidget)
        self.edit_strikerColor.setObjectName("edit_strikerColor")
        self.gridLayout_15.addWidget(self.edit_strikerColor, 4, 1, 1, 1)
        self.btn_defenderColor = QtWidgets.QPushButton(self.defaultColorWidget)
        self.btn_defenderColor.setFlat(False)
        self.btn_defenderColor.setObjectName("btn_defenderColor")
        self.gridLayout_15.addWidget(self.btn_defenderColor, 2, 2, 1, 1)
        self.defaultColorLabel = QtWidgets.QLabel(self.defaultColorWidget)
        self.defaultColorLabel.setObjectName("defaultColorLabel")
        self.gridLayout_15.addWidget(self.defaultColorLabel, 0, 0, 1, 1)
        self.btn_bishopColor = QtWidgets.QPushButton(self.defaultColorWidget)
        self.btn_bishopColor.setFlat(False)
        self.btn_bishopColor.setObjectName("btn_bishopColor")
        self.gridLayout_15.addWidget(self.btn_bishopColor, 5, 2, 1, 1)
        self.defenderColorLabel = QtWidgets.QLabel(self.defaultColorWidget)
        self.defenderColorLabel.setObjectName("defenderColorLabel")
        self.gridLayout_15.addWidget(self.defenderColorLabel, 2, 0, 1, 1)
        self.bishopColorLabel = QtWidgets.QLabel(self.defaultColorWidget)
        self.bishopColorLabel.setObjectName("bishopColorLabel")
        self.gridLayout_15.addWidget(self.bishopColorLabel, 5, 0, 1, 1)
        self.btn_supporterColor = QtWidgets.QPushButton(self.defaultColorWidget)
        self.btn_supporterColor.setFlat(False)
        self.btn_supporterColor.setObjectName("btn_supporterColor")
        self.gridLayout_15.addWidget(self.btn_supporterColor, 3, 2, 1, 1)
        self.strikerColorLabel = QtWidgets.QLabel(self.defaultColorWidget)
        self.strikerColorLabel.setObjectName("strikerColorLabel")
        self.gridLayout_15.addWidget(self.strikerColorLabel, 4, 0, 1, 1)
        self.supporterColorLabel = QtWidgets.QLabel(self.defaultColorWidget)
        self.supporterColorLabel.setObjectName("supporterColorLabel")
        self.gridLayout_15.addWidget(self.supporterColorLabel, 3, 0, 1, 1)
        self.edit_bishopColor = QtWidgets.QLineEdit(self.defaultColorWidget)
        self.edit_bishopColor.setObjectName("edit_bishopColor")
        self.gridLayout_15.addWidget(self.edit_bishopColor, 5, 1, 1, 1)
        self.btn_strikerColor = QtWidgets.QPushButton(self.defaultColorWidget)
        self.btn_strikerColor.setFlat(False)
        self.btn_strikerColor.setObjectName("btn_strikerColor")
        self.gridLayout_15.addWidget(self.btn_strikerColor, 4, 2, 1, 1)
        self.edit_keeperColor = QtWidgets.QLineEdit(self.defaultColorWidget)
        self.edit_keeperColor.setObjectName("edit_keeperColor")
        self.gridLayout_15.addWidget(self.edit_keeperColor, 1, 1, 1, 1)
        self.replacementKeeperColorLabel = QtWidgets.QLabel(self.defaultColorWidget)
        self.replacementKeeperColorLabel.setObjectName("replacementKeeperColorLabel")
        self.gridLayout_15.addWidget(self.replacementKeeperColorLabel, 6, 0, 1, 1)
        self.edit_replacementKeeperColor = QtWidgets.QLineEdit(self.defaultColorWidget)
        self.edit_replacementKeeperColor.setObjectName("edit_replacementKeeperColor")
        self.gridLayout_15.addWidget(self.edit_replacementKeeperColor, 6, 1, 1, 1)
        self.btn_replacementKeeperColor = QtWidgets.QPushButton(self.defaultColorWidget)
        self.btn_replacementKeeperColor.setFlat(False)
        self.btn_replacementKeeperColor.setObjectName("btn_replacementKeeperColor")
        self.gridLayout_15.addWidget(self.btn_replacementKeeperColor, 6, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_15)
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.defaultColorWidget)
        self.searchPositionLabel = QtWidgets.QLabel(self.groupBox_2)
        self.searchPositionLabel.setObjectName("searchPositionLabel")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.searchPositionLabel)
        self.searchPositionCheckbox = QtWidgets.QCheckBox(self.groupBox_2)
        self.searchPositionCheckbox.setChecked(False)
        self.searchPositionCheckbox.setObjectName("searchPositionCheckbox")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.searchPositionCheckbox)
        self.searchPositionDiameterLabel = QtWidgets.QLabel(self.groupBox_2)
        self.searchPositionDiameterLabel.setObjectName("searchPositionDiameterLabel")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.searchPositionDiameterLabel)
        self.spin_searchPositionDiameter = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spin_searchPositionDiameter.setObjectName("spin_searchPositionDiameter")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.spin_searchPositionDiameter)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAccept = QtWidgets.QPushButton(TeamPlayersConfig)
        self.btnAccept.setObjectName("btnAccept")
        self.horizontalLayout.addWidget(self.btnAccept)
        self.btnDiscard = QtWidgets.QPushButton(TeamPlayersConfig)
        self.btnDiscard.setObjectName("btnDiscard")
        self.horizontalLayout.addWidget(self.btnDiscard)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TeamPlayersConfig)
        QtCore.QMetaObject.connectSlotsByName(TeamPlayersConfig)
        TeamPlayersConfig.setTabOrder(self.nameLineEdit, self.spin_center_x)
        TeamPlayersConfig.setTabOrder(self.spin_center_x, self.spin_center_y)
        TeamPlayersConfig.setTabOrder(self.spin_center_y, self.enabledCheckBox)
        TeamPlayersConfig.setTabOrder(self.enabledCheckBox, self.edit_TeamPlayersKeyLambda)
        TeamPlayersConfig.setTabOrder(self.edit_TeamPlayersKeyLambda, self.playerCheckbox)
        TeamPlayersConfig.setTabOrder(self.playerCheckbox, self.spin_poseCircleDiameter)
        TeamPlayersConfig.setTabOrder(self.spin_poseCircleDiameter, self.targetCheckbox)
        TeamPlayersConfig.setTabOrder(self.targetCheckbox, self.spin_targetCircleDiameter)
        TeamPlayersConfig.setTabOrder(self.spin_targetCircleDiameter, self.fovCheckbox)
        TeamPlayersConfig.setTabOrder(self.fovCheckbox, self.spin_maxDistance)
        TeamPlayersConfig.setTabOrder(self.spin_maxDistance, self.spin_cameraOpeningAngle)
        TeamPlayersConfig.setTabOrder(self.spin_cameraOpeningAngle, self.btnAccept)
        TeamPlayersConfig.setTabOrder(self.btnAccept, self.btnDiscard)
        TeamPlayersConfig.setTabOrder(self.btnDiscard, self.scrollArea)

    def retranslateUi(self, TeamPlayersConfig):
        _translate = QtCore.QCoreApplication.translate
        TeamPlayersConfig.setWindowTitle(_translate("TeamPlayersConfig", "Form"))
        self.groupBox.setTitle(_translate("TeamPlayersConfig", "General:"))
        self.nameLabel.setText(_translate("TeamPlayersConfig", "Name:"))
        self.centerLabel.setText(_translate("TeamPlayersConfig", "Center"))
        self.label_center_x.setText(_translate("TeamPlayersConfig", "X:"))
        self.label_center_y.setText(_translate("TeamPlayersConfig", "Y:"))
        self.enabledLabel.setText(_translate("TeamPlayersConfig", "Enabled:"))
        self.groupBox_2.setTitle(_translate("TeamPlayersConfig", "Team robots:"))
        self.poseKeyLabel.setText(_translate("TeamPlayersConfig", "Key:"))
        self.label.setText(_translate("TeamPlayersConfig", "def parse(input):"))
        self.label_2.setText(_translate("TeamPlayersConfig", "return output"))
        self.playerLabel.setText(_translate("TeamPlayersConfig", "Show player position"))
        self.poseCircleDiameterLabel.setText(_translate("TeamPlayersConfig", "poseCircleDiameter:"))
        self.targetLabel.setText(_translate("TeamPlayersConfig", "Show walking target"))
        self.targetCircleDiameterLabel.setText(_translate("TeamPlayersConfig", "targetCircleDiameter:"))
        self.fovLabel.setText(_translate("TeamPlayersConfig", "Show Field-of-View"))
        self.maxDistanceLabel.setText(_translate("TeamPlayersConfig", "maxDistance"))
        self.cameraOpeningAngleLabel.setText(_translate("TeamPlayersConfig", "cameraOpeningAngle"))
        self.keeperColorLabel.setText(_translate("TeamPlayersConfig", "keeperColor:"))
        self.btn_defaultColor.setText(_translate("TeamPlayersConfig", "Pick"))
        self.btn_keeperColor.setText(_translate("TeamPlayersConfig", "Pick"))
        self.btn_defenderColor.setText(_translate("TeamPlayersConfig", "Pick"))
        self.defaultColorLabel.setText(_translate("TeamPlayersConfig", "defaultColor:"))
        self.btn_bishopColor.setText(_translate("TeamPlayersConfig", "Pick"))
        self.defenderColorLabel.setText(_translate("TeamPlayersConfig", "defenderColor:"))
        self.bishopColorLabel.setText(_translate("TeamPlayersConfig", "bishopColor:"))
        self.btn_supporterColor.setText(_translate("TeamPlayersConfig", "Pick"))
        self.strikerColorLabel.setText(_translate("TeamPlayersConfig", "strikerColor:"))
        self.supporterColorLabel.setText(_translate("TeamPlayersConfig", "supporterColor:"))
        self.btn_strikerColor.setText(_translate("TeamPlayersConfig", "Pick"))
        self.replacementKeeperColorLabel.setText(_translate("TeamPlayersConfig", "replacementKeeperColor:"))
        self.btn_replacementKeeperColor.setText(_translate("TeamPlayersConfig", "Pick"))
        self.searchPositionLabel.setText(_translate("TeamPlayersConfig", "Show search position"))
        self.searchPositionDiameterLabel.setText(_translate("TeamPlayersConfig", "searchPositionDiameter:"))
        self.btnAccept.setText(_translate("TeamPlayersConfig", "Accept"))
        self.btnDiscard.setText(_translate("TeamPlayersConfig", "Discard"))

