[package]
name = "hula_types"
version = "0.1.0"
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
path_serde = { workspace = true }
serde = { workspace = true }
zbus = { workspace = true, optional = true }

[features]
default = []

zbus = ["dep:zbus"]
