# Find ittnotify
#
# This module defines
# ITTNOTIFY_INCLUDE_DIRS
# ITTNOTIFY_LIBRARIES
# ITTNOTIFY_FOUND

find_path(ITTNOTIFY_INCLUDE_DIR NAMES ittnotify.h HINTS $ENV{ITTNOTIFY_HOME}/include $ENV{VTUNE_HOME}/include ${VTUNE_HOME}/include NO_CMAKE_FIND_ROOT_PATH)
if (NAO)
	find_library(ITTNOTIFY_LIBRARY NAMES ittnotify HINTS $ENV{ITTNOTIFY_HOME}/lib32 $ENV{VTUNE_HOME}/lib32 ${VTUNE_HOME}/lib32 NO_CMAKE_FIND_ROOT_PATH)
else (NAO)
	find_library(ITTNOTIFY_LIBRARY NAMES ittnotify HINTS $ENV{ITTNOTIFY_HOME}/lib64 $ENV{VTUNE_HOME}/lib64 ${VTUNE_HOME}/lib64 NO_CMAKE_FIND_ROOT_PATH)
endif (NAO)

set(ITTNOTIFY_INCLUDE_DIRS ${ITTNOTIFY_INCLUDE_DIR})
set(ITTNOTIFY_LIBRARIES ${ITTNOTIFY_LIBRARY})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ITTNOTIFY DEFAULT_MSG ITTNOTIFY_LIBRARY ITTNOTIFY_INCLUDE_DIR)

mark_as_advanced(ITTNOTIFY_INCLUDE_DIR ITTNOTIFY_LIBRARY)
