# Find tuhhSDK
#
# This module defines
# TUHHSDK_HOME
# TUHHSDK_INCLUDE_DIRS
# TUHHSDK_LIBRARIES

set(TUHHSDK_HOME ${CMAKE_SOURCE_DIR}/src/tuhhsdk)
set(TUHHSDK_INCLUDE_DIRS ${TUHHSDK_HOME})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(tuhhSDK DEFAULT_MSG TUHHSDK_HOME TUHHSDK_INCLUDE_DIRS)
