[package]
name = "parameter_tester"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = { workspace = true }
framework = { workspace = true }
hulk = { workspace = true }
parameters = { workspace = true }
serde_json = { workspace = true }
types = { workspace = true }
