[project]
name = "mujoco-stubs"
version = "0.3.0"
description = "Stub-files for the mujoco package"
requires-python = ">=3.13"
dependencies = ["mujoco>=3.2.6"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/mujoco-stubs/__init__.pyi"

[tool.hatch.build.targets.wheel]
packages = ["src/mujoco-stubs"]
