[package]
name = "vista"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
eframe.workspace = true
hulk_manifest.workspace = true
hulk_widgets.workspace = true
repository.workspace = true
source_analyzer.workspace = true
tokio.workspace = true
