name: Check for releases
on: push
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

jobs:
  releases:
    name: Check for releases
    runs-on:
      ubuntu-latest
      # - self-hosted
      # - v3
    container:
      image: ghcr.io/hulks/hulk-ci:1.84.1
      # options: --user=1000:1000
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Check for pepsi release
        uses: hulks/rust-release@v1.1
        with:
          title: pepsi
          token: ${{ secrets.GITHUB_TOKEN }}
          cargo: tools/pepsi/Cargo.toml
          dry_run: false
