[package]
name = "nao_camera"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
i2cdev = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
types = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }
