// This module re-exports auto-generated ROS message types
// The actual code is generated at build time and included from OUT_DIR

// Include the CDR-compatible generated code (serde-based)
include!(concat!(env!("OUT_DIR"), "/generated.rs"));

// Accurate size estimation for SHM serialization (trait + primitives)
// Implementations for ROS messages are auto-generated by ros-z-codegen
pub mod size_estimation;

// Re-export the namespaced modules for compatibility
pub use self::ros::*;

// Re-export commonly used items from ros-z for convenience
pub use ros_z::{
    Message,
    entity::{SchemaHash, TypeInfo},
};
